// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPermissionAPI creates a new instance of MockPermissionAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionAPI {
	mock := &MockPermissionAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPermissionAPI is an autogenerated mock type for the PermissionAPI type
type MockPermissionAPI struct {
	mock.Mock
}

type MockPermissionAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPermissionAPI) EXPECT() *MockPermissionAPI_Expecter {
	return &MockPermissionAPI_Expecter{mock: &_m.Mock}
}

// GetPermissionLevel provides a mock function for the type MockPermissionAPI
func (_mock *MockPermissionAPI) GetPermissionLevel(ctx context.Context, owner string, repo string, username string) (*PermissionResult, error) {
	ret := _mock.Called(ctx, owner, repo, username)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissionLevel")
	}

	var r0 *PermissionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*PermissionResult, error)); ok {
		return returnFunc(ctx, owner, repo, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *PermissionResult); ok {
		r0 = returnFunc(ctx, owner, repo, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PermissionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPermissionAPI_GetPermissionLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissionLevel'
type MockPermissionAPI_GetPermissionLevel_Call struct {
	*mock.Call
}

// GetPermissionLevel is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - username string
func (_e *MockPermissionAPI_Expecter) GetPermissionLevel(ctx interface{}, owner interface{}, repo interface{}, username interface{}) *MockPermissionAPI_GetPermissionLevel_Call {
	return &MockPermissionAPI_GetPermissionLevel_Call{Call: _e.mock.On("GetPermissionLevel", ctx, owner, repo, username)}
}

func (_c *MockPermissionAPI_GetPermissionLevel_Call) Run(run func(ctx context.Context, owner string, repo string, username string)) *MockPermissionAPI_GetPermissionLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPermissionAPI_GetPermissionLevel_Call) Return(permissionResult *PermissionResult, err error) *MockPermissionAPI_GetPermissionLevel_Call {
	_c.Call.Return(permissionResult, err)
	return _c
}

func (_c *MockPermissionAPI_GetPermissionLevel_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, username string) (*PermissionResult, error)) *MockPermissionAPI_GetPermissionLevel_Call {
	_c.Call.Return(run)
	return _c
}
