// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package git

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBranchService creates a new instance of MockBranchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchService {
	mock := &MockBranchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBranchService is an autogenerated mock type for the BranchService type
type MockBranchService struct {
	mock.Mock
}

type MockBranchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchService) EXPECT() *MockBranchService_Expecter {
	return &MockBranchService_Expecter{mock: &_m.Mock}
}

// BranchExists provides a mock function for the type MockBranchService
func (_mock *MockBranchService) BranchExists(ctx context.Context, repoPath string, branchName string) bool {
	ret := _mock.Called(ctx, repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for BranchExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, repoPath, branchName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBranchService_BranchExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BranchExists'
type MockBranchService_BranchExists_Call struct {
	*mock.Call
}

// BranchExists is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
func (_e *MockBranchService_Expecter) BranchExists(ctx interface{}, repoPath interface{}, branchName interface{}) *MockBranchService_BranchExists_Call {
	return &MockBranchService_BranchExists_Call{Call: _e.mock.On("BranchExists", ctx, repoPath, branchName)}
}

func (_c *MockBranchService_BranchExists_Call) Run(run func(ctx context.Context, repoPath string, branchName string)) *MockBranchService_BranchExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchService_BranchExists_Call) Return(b bool) *MockBranchService_BranchExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBranchService_BranchExists_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string) bool) *MockBranchService_BranchExists_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranch provides a mock function for the type MockBranchService
func (_mock *MockBranchService) CreateBranch(ctx context.Context, repoPath string, branchName string) error {
	ret := _mock.Called(ctx, repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockBranchService_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
func (_e *MockBranchService_Expecter) CreateBranch(ctx interface{}, repoPath interface{}, branchName interface{}) *MockBranchService_CreateBranch_Call {
	return &MockBranchService_CreateBranch_Call{Call: _e.mock.On("CreateBranch", ctx, repoPath, branchName)}
}

func (_c *MockBranchService_CreateBranch_Call) Run(run func(ctx context.Context, repoPath string, branchName string)) *MockBranchService_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchService_CreateBranch_Call) Return(err error) *MockBranchService_CreateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_CreateBranch_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string) error) *MockBranchService_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranchFromRef provides a mock function for the type MockBranchService
func (_mock *MockBranchService) CreateBranchFromRef(ctx context.Context, repoPath string, branchName string, startPoint string) error {
	ret := _mock.Called(ctx, repoPath, branchName, startPoint)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranchFromRef")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branchName, startPoint)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_CreateBranchFromRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranchFromRef'
type MockBranchService_CreateBranchFromRef_Call struct {
	*mock.Call
}

// CreateBranchFromRef is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
//   - startPoint string
func (_e *MockBranchService_Expecter) CreateBranchFromRef(ctx interface{}, repoPath interface{}, branchName interface{}, startPoint interface{}) *MockBranchService_CreateBranchFromRef_Call {
	return &MockBranchService_CreateBranchFromRef_Call{Call: _e.mock.On("CreateBranchFromRef", ctx, repoPath, branchName, startPoint)}
}

func (_c *MockBranchService_CreateBranchFromRef_Call) Run(run func(ctx context.Context, repoPath string, branchName string, startPoint string)) *MockBranchService_CreateBranchFromRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBranchService_CreateBranchFromRef_Call) Return(err error) *MockBranchService_CreateBranchFromRef_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_CreateBranchFromRef_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string, startPoint string) error) *MockBranchService_CreateBranchFromRef_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranch provides a mock function for the type MockBranchService
func (_mock *MockBranchService) DeleteBranch(ctx context.Context, repoPath string, branchName string) error {
	ret := _mock.Called(ctx, repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_DeleteBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranch'
type MockBranchService_DeleteBranch_Call struct {
	*mock.Call
}

// DeleteBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
func (_e *MockBranchService_Expecter) DeleteBranch(ctx interface{}, repoPath interface{}, branchName interface{}) *MockBranchService_DeleteBranch_Call {
	return &MockBranchService_DeleteBranch_Call{Call: _e.mock.On("DeleteBranch", ctx, repoPath, branchName)}
}

func (_c *MockBranchService_DeleteBranch_Call) Run(run func(ctx context.Context, repoPath string, branchName string)) *MockBranchService_DeleteBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchService_DeleteBranch_Call) Return(err error) *MockBranchService_DeleteBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_DeleteBranch_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string) error) *MockBranchService_DeleteBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBranchForce provides a mock function for the type MockBranchService
func (_mock *MockBranchService) DeleteBranchForce(ctx context.Context, repoPath string, branchName string) error {
	ret := _mock.Called(ctx, repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBranchForce")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_DeleteBranchForce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBranchForce'
type MockBranchService_DeleteBranchForce_Call struct {
	*mock.Call
}

// DeleteBranchForce is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
func (_e *MockBranchService_Expecter) DeleteBranchForce(ctx interface{}, repoPath interface{}, branchName interface{}) *MockBranchService_DeleteBranchForce_Call {
	return &MockBranchService_DeleteBranchForce_Call{Call: _e.mock.On("DeleteBranchForce", ctx, repoPath, branchName)}
}

func (_c *MockBranchService_DeleteBranchForce_Call) Run(run func(ctx context.Context, repoPath string, branchName string)) *MockBranchService_DeleteBranchForce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchService_DeleteBranchForce_Call) Return(err error) *MockBranchService_DeleteBranchForce_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_DeleteBranchForce_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string) error) *MockBranchService_DeleteBranchForce_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateBranchName provides a mock function for the type MockBranchService
func (_mock *MockBranchService) GenerateBranchName(issueNumber int, title string) string {
	ret := _mock.Called(issueNumber, title)

	if len(ret) == 0 {
		panic("no return value specified for GenerateBranchName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(int, string) string); ok {
		r0 = returnFunc(issueNumber, title)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBranchService_GenerateBranchName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateBranchName'
type MockBranchService_GenerateBranchName_Call struct {
	*mock.Call
}

// GenerateBranchName is a helper method to define mock.On call
//   - issueNumber int
//   - title string
func (_e *MockBranchService_Expecter) GenerateBranchName(issueNumber interface{}, title interface{}) *MockBranchService_GenerateBranchName_Call {
	return &MockBranchService_GenerateBranchName_Call{Call: _e.mock.On("GenerateBranchName", issueNumber, title)}
}

func (_c *MockBranchService_GenerateBranchName_Call) Run(run func(issueNumber int, title string)) *MockBranchService_GenerateBranchName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBranchService_GenerateBranchName_Call) Return(s string) *MockBranchService_GenerateBranchName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBranchService_GenerateBranchName_Call) RunAndReturn(run func(issueNumber int, title string) string) *MockBranchService_GenerateBranchName_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function for the type MockBranchService
func (_mock *MockBranchService) ListBranches(ctx context.Context, repoPath string) ([]BranchInfo, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []BranchInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]BranchInfo, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []BranchInfo); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BranchInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBranchService_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockBranchService_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockBranchService_Expecter) ListBranches(ctx interface{}, repoPath interface{}) *MockBranchService_ListBranches_Call {
	return &MockBranchService_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx, repoPath)}
}

func (_c *MockBranchService_ListBranches_Call) Run(run func(ctx context.Context, repoPath string)) *MockBranchService_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBranchService_ListBranches_Call) Return(branchInfos []BranchInfo, err error) *MockBranchService_ListBranches_Call {
	_c.Call.Return(branchInfos, err)
	return _c
}

func (_c *MockBranchService_ListBranches_Call) RunAndReturn(run func(ctx context.Context, repoPath string) ([]BranchInfo, error)) *MockBranchService_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchBranch provides a mock function for the type MockBranchService
func (_mock *MockBranchService) SwitchBranch(ctx context.Context, repoPath string, branchName string) error {
	ret := _mock.Called(ctx, repoPath, branchName)

	if len(ret) == 0 {
		panic("no return value specified for SwitchBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_SwitchBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchBranch'
type MockBranchService_SwitchBranch_Call struct {
	*mock.Call
}

// SwitchBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branchName string
func (_e *MockBranchService_Expecter) SwitchBranch(ctx interface{}, repoPath interface{}, branchName interface{}) *MockBranchService_SwitchBranch_Call {
	return &MockBranchService_SwitchBranch_Call{Call: _e.mock.On("SwitchBranch", ctx, repoPath, branchName)}
}

func (_c *MockBranchService_SwitchBranch_Call) Run(run func(ctx context.Context, repoPath string, branchName string)) *MockBranchService_SwitchBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchService_SwitchBranch_Call) Return(err error) *MockBranchService_SwitchBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_SwitchBranch_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branchName string) error) *MockBranchService_SwitchBranch_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBranchName provides a mock function for the type MockBranchService
func (_mock *MockBranchService) ValidateBranchName(branchName string) error {
	ret := _mock.Called(branchName)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBranchName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(branchName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchService_ValidateBranchName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBranchName'
type MockBranchService_ValidateBranchName_Call struct {
	*mock.Call
}

// ValidateBranchName is a helper method to define mock.On call
//   - branchName string
func (_e *MockBranchService_Expecter) ValidateBranchName(branchName interface{}) *MockBranchService_ValidateBranchName_Call {
	return &MockBranchService_ValidateBranchName_Call{Call: _e.mock.On("ValidateBranchName", branchName)}
}

func (_c *MockBranchService_ValidateBranchName_Call) Run(run func(branchName string)) *MockBranchService_ValidateBranchName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBranchService_ValidateBranchName_Call) Return(err error) *MockBranchService_ValidateBranchName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchService_ValidateBranchName_Call) RunAndReturn(run func(branchName string) error) *MockBranchService_ValidateBranchName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConflictDetector creates a new instance of MockConflictDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConflictDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConflictDetector {
	mock := &MockConflictDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConflictDetector is an autogenerated mock type for the ConflictDetector type
type MockConflictDetector struct {
	mock.Mock
}

type MockConflictDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConflictDetector) EXPECT() *MockConflictDetector_Expecter {
	return &MockConflictDetector_Expecter{mock: &_m.Mock}
}

// AbortMerge provides a mock function for the type MockConflictDetector
func (_mock *MockConflictDetector) AbortMerge(ctx context.Context, repoPath string) error {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for AbortMerge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConflictDetector_AbortMerge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortMerge'
type MockConflictDetector_AbortMerge_Call struct {
	*mock.Call
}

// AbortMerge is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockConflictDetector_Expecter) AbortMerge(ctx interface{}, repoPath interface{}) *MockConflictDetector_AbortMerge_Call {
	return &MockConflictDetector_AbortMerge_Call{Call: _e.mock.On("AbortMerge", ctx, repoPath)}
}

func (_c *MockConflictDetector_AbortMerge_Call) Run(run func(ctx context.Context, repoPath string)) *MockConflictDetector_AbortMerge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConflictDetector_AbortMerge_Call) Return(err error) *MockConflictDetector_AbortMerge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConflictDetector_AbortMerge_Call) RunAndReturn(run func(ctx context.Context, repoPath string) error) *MockConflictDetector_AbortMerge_Call {
	_c.Call.Return(run)
	return _c
}

// DetectConflicts provides a mock function for the type MockConflictDetector
func (_mock *MockConflictDetector) DetectConflicts(ctx context.Context, repoPath string, sourceBranch string, targetBranch string) ([]ConflictInfo, error) {
	ret := _mock.Called(ctx, repoPath, sourceBranch, targetBranch)

	if len(ret) == 0 {
		panic("no return value specified for DetectConflicts")
	}

	var r0 []ConflictInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]ConflictInfo, error)); ok {
		return returnFunc(ctx, repoPath, sourceBranch, targetBranch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []ConflictInfo); ok {
		r0 = returnFunc(ctx, repoPath, sourceBranch, targetBranch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConflictInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, repoPath, sourceBranch, targetBranch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConflictDetector_DetectConflicts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectConflicts'
type MockConflictDetector_DetectConflicts_Call struct {
	*mock.Call
}

// DetectConflicts is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - sourceBranch string
//   - targetBranch string
func (_e *MockConflictDetector_Expecter) DetectConflicts(ctx interface{}, repoPath interface{}, sourceBranch interface{}, targetBranch interface{}) *MockConflictDetector_DetectConflicts_Call {
	return &MockConflictDetector_DetectConflicts_Call{Call: _e.mock.On("DetectConflicts", ctx, repoPath, sourceBranch, targetBranch)}
}

func (_c *MockConflictDetector_DetectConflicts_Call) Run(run func(ctx context.Context, repoPath string, sourceBranch string, targetBranch string)) *MockConflictDetector_DetectConflicts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockConflictDetector_DetectConflicts_Call) Return(conflictInfos []ConflictInfo, err error) *MockConflictDetector_DetectConflicts_Call {
	_c.Call.Return(conflictInfos, err)
	return _c
}

func (_c *MockConflictDetector_DetectConflicts_Call) RunAndReturn(run func(ctx context.Context, repoPath string, sourceBranch string, targetBranch string) ([]ConflictInfo, error)) *MockConflictDetector_DetectConflicts_Call {
	_c.Call.Return(run)
	return _c
}

// GetConflictedFiles provides a mock function for the type MockConflictDetector
func (_mock *MockConflictDetector) GetConflictedFiles(ctx context.Context, repoPath string) ([]string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for GetConflictedFiles")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConflictDetector_GetConflictedFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConflictedFiles'
type MockConflictDetector_GetConflictedFiles_Call struct {
	*mock.Call
}

// GetConflictedFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockConflictDetector_Expecter) GetConflictedFiles(ctx interface{}, repoPath interface{}) *MockConflictDetector_GetConflictedFiles_Call {
	return &MockConflictDetector_GetConflictedFiles_Call{Call: _e.mock.On("GetConflictedFiles", ctx, repoPath)}
}

func (_c *MockConflictDetector_GetConflictedFiles_Call) Run(run func(ctx context.Context, repoPath string)) *MockConflictDetector_GetConflictedFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConflictDetector_GetConflictedFiles_Call) Return(strings []string, err error) *MockConflictDetector_GetConflictedFiles_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockConflictDetector_GetConflictedFiles_Call) RunAndReturn(run func(ctx context.Context, repoPath string) ([]string, error)) *MockConflictDetector_GetConflictedFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetMergeStatus provides a mock function for the type MockConflictDetector
func (_mock *MockConflictDetector) GetMergeStatus(ctx context.Context, repoPath string) (*MergeStatus, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for GetMergeStatus")
	}

	var r0 *MergeStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*MergeStatus, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *MergeStatus); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MergeStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConflictDetector_GetMergeStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMergeStatus'
type MockConflictDetector_GetMergeStatus_Call struct {
	*mock.Call
}

// GetMergeStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockConflictDetector_Expecter) GetMergeStatus(ctx interface{}, repoPath interface{}) *MockConflictDetector_GetMergeStatus_Call {
	return &MockConflictDetector_GetMergeStatus_Call{Call: _e.mock.On("GetMergeStatus", ctx, repoPath)}
}

func (_c *MockConflictDetector_GetMergeStatus_Call) Run(run func(ctx context.Context, repoPath string)) *MockConflictDetector_GetMergeStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConflictDetector_GetMergeStatus_Call) Return(mergeStatus *MergeStatus, err error) *MockConflictDetector_GetMergeStatus_Call {
	_c.Call.Return(mergeStatus, err)
	return _c
}

func (_c *MockConflictDetector_GetMergeStatus_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (*MergeStatus, error)) *MockConflictDetector_GetMergeStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HasConflicts provides a mock function for the type MockConflictDetector
func (_mock *MockConflictDetector) HasConflicts(ctx context.Context, repoPath string) bool {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for HasConflicts")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockConflictDetector_HasConflicts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasConflicts'
type MockConflictDetector_HasConflicts_Call struct {
	*mock.Call
}

// HasConflicts is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockConflictDetector_Expecter) HasConflicts(ctx interface{}, repoPath interface{}) *MockConflictDetector_HasConflicts_Call {
	return &MockConflictDetector_HasConflicts_Call{Call: _e.mock.On("HasConflicts", ctx, repoPath)}
}

func (_c *MockConflictDetector_HasConflicts_Call) Run(run func(ctx context.Context, repoPath string)) *MockConflictDetector_HasConflicts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConflictDetector_HasConflicts_Call) Return(b bool) *MockConflictDetector_HasConflicts_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockConflictDetector_HasConflicts_Call) RunAndReturn(run func(ctx context.Context, repoPath string) bool) *MockConflictDetector_HasConflicts_Call {
	_c.Call.Return(run)
	return _c
}
