/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export interface ApiError {
	code?: string;
	/** Details contains additional error context (field names, validation rules, etc.)
  Type varies by error code: map[string]string for validation, string for general errors */
	details?: unknown;
	message?: string;
}
