/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { AuditSummaryByOperation } from "./auditSummaryByOperation";
import type { AuditSummaryByResult } from "./auditSummaryByResult";

export interface AuditSummary {
	averageDurationMs?: number;
	byOperation?: AuditSummaryByOperation;
	byResult?: AuditSummaryByResult;
	firstTimestamp?: string;
	lastTimestamp?: string;
	sessionId?: string;
	totalCount?: number;
	totalDurationMs?: number;
}
