/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { ActorRole } from "./actorRole";
import type { AuditLogParameters } from "./auditLogParameters";
import type { AuditLogResult } from "./auditLogResult";
import type { OperationType } from "./operationType";

export interface AuditLog {
	id: string;
	timestamp: string;
	sessionId?: string;
	repository?: string;
	issueNumber?: number;
	actor?: string;
	actorRole?: ActorRole;
	operation: OperationType;
	resourceType?: string;
	resourceId?: string;
	parameters?: AuditLogParameters;
	result: AuditLogResult;
	/** Duration in milliseconds */
	duration?: number;
	output?: string;
	error?: string;
}
