/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type ClarificationStatus =
	(typeof ClarificationStatus)[keyof typeof ClarificationStatus];

export const ClarificationStatus = {
	in_progress: "in_progress",
	completed: "completed",
} as const;
