/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { ClarityDimensionChecks } from "./clarityDimensionChecks";

export interface ClarityDimension {
	/** @minimum 0 */
	score?: number;
	/** @minimum 0 */
	maxScore?: number;
	checks?: ClarityDimensionChecks;
}
