/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { ClarificationStatus } from "./clarificationStatus";
import type { ClarityDimensions } from "./clarityDimensions";
import type { ConversationTurn } from "./conversationTurn";

export interface Clarification {
	id?: string;
	confirmedPoints?: string[];
	pendingQuestions?: string[];
	history?: ConversationTurn[];
	status?: ClarificationStatus;
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	clarityScore?: number;
	clarityDimensions?: ClarityDimensions;
}
