/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { ClarityDimension } from "./clarityDimension";
import type { ClarityDimensionsGrade } from "./clarityDimensionsGrade";

export interface ClarityDimensions {
	completeness?: ClarityDimension;
	clarity?: ClarityDimension;
	consistency?: ClarityDimension;
	feasibility?: ClarityDimension;
	testability?: ClarityDimension;
	/**
	 * @minimum 0
	 * @maximum 100
	 */
	totalScore?: number;
	grade?: ClarityDimensionsGrade;
	canAutoProceed?: boolean;
}
