/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type ClarityDimensionsGrade =
	(typeof ClarityDimensionsGrade)[keyof typeof ClarityDimensionsGrade];

export const ClarityDimensionsGrade = {
	高清晰度: "高清晰度",
	中清晰度: "中清晰度",
	低清晰度: "低清晰度",
	不清晰: "不清晰",
} as const;
