/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { DetectedTool } from "./detectedTool";

export interface DetectedProject {
	confidence?: number;
	detectedAt?: string;
	detectedTools?: DetectedTool[];
	languages?: string[];
	primaryLanguage?: string;
	type?: string;
}
