/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { TestResult } from "./testResult";

export interface ExecutionResult {
	/** Execution duration in milliseconds */
	duration?: number;
	/** Execution output/logs */
	output?: string;
	/** Whether execution succeeded */
	success?: boolean;
	/** Test results (if applicable) */
	testResults?: TestResult[];
}
