/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1SessionsStatus =
	(typeof GetApiV1SessionsStatus)[keyof typeof GetApiV1SessionsStatus];

export const GetApiV1SessionsStatus = {
	active: "active",
	paused: "paused",
	completed: "completed",
	terminated: "terminated",
} as const;
