/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1SessionsSessionIdTasksParams = {
	/**
	 * Page number (default: 1)
	 * @minimum 1
	 */
	page?: number;
	/**
	 * Page size (default: 20, max: 100)
	 * @minimum 1
	 * @maximum 100
	 */
	pageSize?: number;
	/**
	 * Filter by status (pending, in_progress, completed, failed, skipped)
	 */
	status?: string;
};
