/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type GetApiV1SessionsStage =
	(typeof GetApiV1SessionsStage)[keyof typeof GetApiV1SessionsStage];

export const GetApiV1SessionsStage = {
	clarification: "clarification",
	design: "design",
	task_breakdown: "task_breakdown",
	execution: "execution",
	pull_request: "pull_request",
	completed: "completed",
} as const;
