/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { GithubComRyuybLitchiInternalApplicationServerHandlerUserUpdateUserRequestRole } from "./githubComRyuybLitchiInternalApplicationServerHandlerUserUpdateUserRequestRole";

export interface GithubComRyuybLitchiInternalApplicationServerHandlerUserUpdateUserRequest {
	/** @minLength 6 */
	password?: string;
	role?: GithubComRyuybLitchiInternalApplicationServerHandlerUserUpdateUserRequestRole;
	/**
	 * @minLength 3
	 * @maxLength 50
	 */
	username?: string;
}
