/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { HealthCheckItem } from "./healthCheckItem";

export interface HealthDetail {
	checks?: HealthCheckItem[];
	/** healthy, degraded, unhealthy */
	status?: string;
	timestamp?: string;
	version?: string;
}
