/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

/**
 * Audit log operation type enum
 */
export type OperationType = (typeof OperationType)[keyof typeof OperationType];

export const OperationType = {
	session_start: "session_start",
	session_pause: "session_pause",
	session_resume: "session_resume",
	session_terminate: "session_terminate",
	stage_transition: "stage_transition",
	agent_call: "agent_call",
	tool_use: "tool_use",
	file_read: "file_read",
	file_write: "file_write",
	bash_execute: "bash_execute",
	git_operation: "git_operation",
	pr_create: "pr_create",
	approval_request: "approval_request",
	approval_decision: "approval_decision",
} as const;
