/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export interface PaginationParams {
	/** @minimum 1 */
	page?: number;
	/**
	 * @minimum 1
	 * @maximum 100
	 */
	pageSize?: number;
}
