/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { RepoConfig } from "./repoConfig";

export interface Repository {
	config?: RepoConfig;
	enabled?: boolean;
	id?: string;
	name?: string;
}
