/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type RollbackSessionTargetStage =
	(typeof RollbackSessionTargetStage)[keyof typeof RollbackSessionTargetStage];

export const RollbackSessionTargetStage = {
	clarification: "clarification",
	design: "design",
	task_breakdown: "task_breakdown",
} as const;
