/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { Design } from "./design";
import type { Execution } from "./execution";
import type { Issue } from "./issue";
import type { SessionCurrentStage } from "./sessionCurrentStage";
import type { SessionStatus } from "./sessionStatus";
import type { Task } from "./task";

export interface Session {
	createdAt?: string;
	currentStage?: SessionCurrentStage;
	design?: Design;
	execution?: Execution;
	id?: string;
	issue?: Issue;
	issueNumber?: number;
	issueTitle?: string;
	prNumber?: number;
	repository?: string;
	status?: SessionStatus;
	tasks?: Task[];
	updatedAt?: string;
}
