/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

/**
 * Workflow stage enum
 */
export type Stage = (typeof Stage)[keyof typeof Stage];

export const Stage = {
	clarification: "clarification",
	design: "design",
	task_breakdown: "task_breakdown",
	execution: "execution",
	pull_request: "pull_request",
	completed: "completed",
} as const;
