/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { Task } from "./task";

export interface TaskList {
	allCompleted?: boolean;
	completed?: number;
	failed?: number;
	hasFailedTask?: boolean;
	inProgress?: number;
	maxRetryLimit?: number;
	page?: number;
	pageSize?: number;
	pending?: number;
	sessionId?: string;
	skipped?: number;
	tasks?: Task[];
	/** Pagination info (based on filtered results) */
	totalItems?: number;
	totalPages?: number;
	/** Total tasks in session (unfiltered) */
	totalTasks?: number;
}
