/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { DependencyStatus } from "./dependencyStatus";
import type { ExecutionResult } from "./executionResult";

export interface TaskStatus {
	dependencies?: DependencyStatus[];
	description?: string;
	executionResult?: ExecutionResult;
	failureReason?: string;
	order?: number;
	retryCount?: number;
	sessionId?: string;
	status?: string;
	statusDisplayName?: string;
	suggestion?: string;
	taskId?: string;
}
