/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export interface Task {
	canExecute?: boolean;
	dependencies?: string[];
	description?: string;
	failureReason?: string;
	id?: string;
	order?: number;
	retryCount?: number;
	status?: string;
	statusDisplay?: string;
	suggestion?: string;
}
