/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { ExecutionResult } from "./executionResult";
import type { TaskStatus } from "./taskStatus";

export interface Task {
	id: string;
	description: string;
	status: TaskStatus;
	dependencies?: string[];
	executionResult?: ExecutionResult;
	/** @minimum 0 */
	retryCount?: number;
	failureReason?: string;
	suggestion?: string;
	createdAt?: string;
	updatedAt?: string;
}
