/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { AgentConfigUpdate } from "./agentConfigUpdate";
import type { AuditConfigUpdate } from "./auditConfigUpdate";
import type { ClarityConfigUpdate } from "./clarityConfigUpdate";
import type { ComplexityConfigUpdate } from "./complexityConfigUpdate";
import type { GitConfigUpdate } from "./gitConfigUpdate";

export interface UpdateConfig {
	agent?: AgentConfigUpdate;
	audit?: AuditConfigUpdate;
	clarity?: ClarityConfigUpdate;
	complexity?: ComplexityConfigUpdate;
	git?: GitConfigUpdate;
}
