/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

export type UserUpdateRequestRole =
	(typeof UserUpdateRequestRole)[keyof typeof UserUpdateRequestRole];

export const UserUpdateRequestRole = {
	admin: "admin",
	viewer: "viewer",
} as const;
