/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { UserCreateRequestRole } from "./userCreateRequestRole";

export interface UserCreateRequest {
	/** @minLength 6 */
	password: string;
	role: UserCreateRequestRole;
	/**
	 * @minLength 3
	 * @maxLength 50
	 */
	username: string;
}
