/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */
import type { Clarification } from "./clarification";
import type { Design } from "./design";
import type { Execution } from "./execution";
import type { Issue } from "./issue";
import type { Stage } from "./stage";
import type { Task } from "./task";

export interface WorkSession {
	id: string;
	stage: Stage;
	issue: Issue;
	clarification?: Clarification;
	design?: Design;
	tasks?: Task[];
	execution?: Execution;
	paused?: boolean;
	terminated?: boolean;
	createdAt?: string;
	updatedAt?: string;
}
