/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type {
	ErrorResponse,
	ListSessions200,
	ListSessionsParams,
	WorkSession,
} from "../schemas";

/**
 * Get a paginated list of work sessions
 * @summary List work sessions
 */
export type listSessionsResponse200 = {
	data: ListSessions200;
	status: 200;
};

export type listSessionsResponse400 = {
	data: ErrorResponse;
	status: 400;
};

export type listSessionsResponseSuccess = listSessionsResponse200 & {
	headers: Headers;
};
export type listSessionsResponseError = listSessionsResponse400 & {
	headers: Headers;
};

export type listSessionsResponse =
	| listSessionsResponseSuccess
	| listSessionsResponseError;

export const getListSessionsUrl = (params?: ListSessionsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/sessions?${stringifiedParams}`
		: `/sessions`;
};

export const listSessions = async (
	params?: ListSessionsParams,
	options?: RequestInit,
): Promise<listSessionsResponse> => {
	const res = await fetch(getListSessionsUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listSessionsResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as listSessionsResponse;
};

export const getListSessionsQueryKey = (params?: ListSessionsParams) => {
	return [`/sessions`, ...(params ? [params] : [])] as const;
};

export const getListSessionsQueryOptions = <
	TData = Awaited<ReturnType<typeof listSessions>>,
	TError = ErrorResponse,
>(
	params?: ListSessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListSessionsQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({
		signal,
	}) => listSessions(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listSessions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSessionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof listSessions>>
>;
export type ListSessionsQueryError = ErrorResponse;

export function useListSessions<
	TData = Awaited<ReturnType<typeof listSessions>>,
	TError = ErrorResponse,
>(
	params: undefined | ListSessionsParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSessions>>,
					TError,
					Awaited<ReturnType<typeof listSessions>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSessions<
	TData = Awaited<ReturnType<typeof listSessions>>,
	TError = ErrorResponse,
>(
	params?: ListSessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listSessions>>,
					TError,
					Awaited<ReturnType<typeof listSessions>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListSessions<
	TData = Awaited<ReturnType<typeof listSessions>>,
	TError = ErrorResponse,
>(
	params?: ListSessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List work sessions
 */

export function useListSessions<
	TData = Awaited<ReturnType<typeof listSessions>>,
	TError = ErrorResponse,
>(
	params?: ListSessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListSessionsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve a single work session by its ID
 * @summary Get work session by ID
 */
export type getSessionResponse200 = {
	data: WorkSession;
	status: 200;
};

export type getSessionResponse404 = {
	data: ErrorResponse;
	status: 404;
};

export type getSessionResponseSuccess = getSessionResponse200 & {
	headers: Headers;
};
export type getSessionResponseError = getSessionResponse404 & {
	headers: Headers;
};

export type getSessionResponse =
	| getSessionResponseSuccess
	| getSessionResponseError;

export const getGetSessionUrl = (id: string) => {
	return `/sessions/${id}`;
};

export const getSession = async (
	id: string,
	options?: RequestInit,
): Promise<getSessionResponse> => {
	const res = await fetch(getGetSessionUrl(id), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getSessionResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getSessionResponse;
};

export const getGetSessionQueryKey = (id: string) => {
	return [`/sessions/${id}`] as const;
};

export const getGetSessionQueryOptions = <
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorResponse,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetSessionQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getSession>>> = ({
		signal,
	}) => getSession(id, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getSession>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSessionQueryResult = NonNullable<
	Awaited<ReturnType<typeof getSession>>
>;
export type GetSessionQueryError = ErrorResponse;

export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorResponse,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSession>>,
					TError,
					Awaited<ReturnType<typeof getSession>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorResponse,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getSession>>,
					TError,
					Awaited<ReturnType<typeof getSession>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorResponse,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work session by ID
 */

export function useGetSession<
	TData = Awaited<ReturnType<typeof getSession>>,
	TError = ErrorResponse,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getSession>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetSessionQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
