/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../../lib/custom-fetch";

import { customFetch } from "../../lib/custom-fetch";
import type {
	ApiError,
	GetApiV1SessionsParams,
	PaginatedResponseSession,
	PostApiV1SessionsIdPauseBody,
	PostApiV1SessionsIdRestartBody,
	PostApiV1SessionsIdResumeBody,
	PostApiV1SessionsIdRollbackBody,
	PostApiV1SessionsIdTerminateBody,
	Session,
} from "../schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves a paginated list of work sessions with optional filtering by status, stage, and repository
 * @summary List work sessions
 */
export type getApiV1SessionsResponse200 = {
	data: PaginatedResponseSession;
	status: 200;
};

export type getApiV1SessionsResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1SessionsResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1SessionsResponseSuccess = getApiV1SessionsResponse200 & {
	headers: Headers;
};
export type getApiV1SessionsResponseError = (
	| getApiV1SessionsResponse400
	| getApiV1SessionsResponse500
) & {
	headers: Headers;
};

export type getApiV1SessionsResponse =
	| getApiV1SessionsResponseSuccess
	| getApiV1SessionsResponseError;

export const getGetApiV1SessionsUrl = (params?: GetApiV1SessionsParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/sessions?${stringifiedParams}`
		: `/api/v1/sessions`;
};

export const getApiV1Sessions = async (
	params?: GetApiV1SessionsParams,
	options?: RequestInit,
): Promise<getApiV1SessionsResponse> => {
	return customFetch<getApiV1SessionsResponse>(getGetApiV1SessionsUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGetApiV1SessionsQueryKey = (
	params?: GetApiV1SessionsParams,
) => {
	return [`/api/v1/sessions`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1SessionsQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Sessions>>,
	TError = ErrorType<ApiError>,
>(
	params?: GetApiV1SessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Sessions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1SessionsQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1Sessions>>
	> = ({ signal }) => getApiV1Sessions(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Sessions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1SessionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Sessions>>
>;
export type GetApiV1SessionsQueryError = ErrorType<ApiError>;

export function useGetApiV1Sessions<
	TData = Awaited<ReturnType<typeof getApiV1Sessions>>,
	TError = ErrorType<ApiError>,
>(
	params: undefined | GetApiV1SessionsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Sessions>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Sessions>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Sessions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Sessions<
	TData = Awaited<ReturnType<typeof getApiV1Sessions>>,
	TError = ErrorType<ApiError>,
>(
	params?: GetApiV1SessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Sessions>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Sessions>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Sessions>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Sessions<
	TData = Awaited<ReturnType<typeof getApiV1Sessions>>,
	TError = ErrorType<ApiError>,
>(
	params?: GetApiV1SessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Sessions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List work sessions
 */

export function useGetApiV1Sessions<
	TData = Awaited<ReturnType<typeof getApiV1Sessions>>,
	TError = ErrorType<ApiError>,
>(
	params?: GetApiV1SessionsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Sessions>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1SessionsQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves a work session by its unique identifier
 * @summary Get work session
 */
export type getApiV1SessionsIdResponse200 = {
	data: Session;
	status: 200;
};

export type getApiV1SessionsIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1SessionsIdResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1SessionsIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1SessionsIdResponseSuccess =
	getApiV1SessionsIdResponse200 & {
		headers: Headers;
	};
export type getApiV1SessionsIdResponseError = (
	| getApiV1SessionsIdResponse400
	| getApiV1SessionsIdResponse404
	| getApiV1SessionsIdResponse500
) & {
	headers: Headers;
};

export type getApiV1SessionsIdResponse =
	| getApiV1SessionsIdResponseSuccess
	| getApiV1SessionsIdResponseError;

export const getGetApiV1SessionsIdUrl = (id: string) => {
	return `/api/v1/sessions/${id}`;
};

export const getApiV1SessionsId = async (
	id: string,
	options?: RequestInit,
): Promise<getApiV1SessionsIdResponse> => {
	return customFetch<getApiV1SessionsIdResponse>(getGetApiV1SessionsIdUrl(id), {
		...options,
		method: "GET",
	});
};

export const getGetApiV1SessionsIdQueryKey = (id: string) => {
	return [`/api/v1/sessions/${id}`] as const;
};

export const getGetApiV1SessionsIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1SessionsId>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1SessionsIdQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1SessionsId>>
	> = ({ signal }) => getApiV1SessionsId(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1SessionsId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1SessionsIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1SessionsId>>
>;
export type GetApiV1SessionsIdQueryError = ErrorType<ApiError>;

export function useGetApiV1SessionsId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsId>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsId>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsId>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsId>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work session
 */

export function useGetApiV1SessionsId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsId>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsId>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1SessionsIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieves a work session with complete details including issue info, design content, task list, and execution context
 * @summary Get session details
 */
export type getApiV1SessionsIdDetailResponse200 = {
	data: Session;
	status: 200;
};

export type getApiV1SessionsIdDetailResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1SessionsIdDetailResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1SessionsIdDetailResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1SessionsIdDetailResponseSuccess =
	getApiV1SessionsIdDetailResponse200 & {
		headers: Headers;
	};
export type getApiV1SessionsIdDetailResponseError = (
	| getApiV1SessionsIdDetailResponse400
	| getApiV1SessionsIdDetailResponse404
	| getApiV1SessionsIdDetailResponse500
) & {
	headers: Headers;
};

export type getApiV1SessionsIdDetailResponse =
	| getApiV1SessionsIdDetailResponseSuccess
	| getApiV1SessionsIdDetailResponseError;

export const getGetApiV1SessionsIdDetailUrl = (id: string) => {
	return `/api/v1/sessions/${id}/detail`;
};

export const getApiV1SessionsIdDetail = async (
	id: string,
	options?: RequestInit,
): Promise<getApiV1SessionsIdDetailResponse> => {
	return customFetch<getApiV1SessionsIdDetailResponse>(
		getGetApiV1SessionsIdDetailUrl(id),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetApiV1SessionsIdDetailQueryKey = (id: string) => {
	return [`/api/v1/sessions/${id}/detail`] as const;
};

export const getGetApiV1SessionsIdDetailQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1SessionsIdDetailQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>
	> = ({ signal }) =>
		getApiV1SessionsIdDetail(id, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1SessionsIdDetailQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>
>;
export type GetApiV1SessionsIdDetailQueryError = ErrorType<ApiError>;

export function useGetApiV1SessionsIdDetail<
	TData = Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsIdDetail<
	TData = Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsIdDetail<
	TData = Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get session details
 */

export function useGetApiV1SessionsIdDetail<
	TData = Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
	TError = ErrorType<ApiError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsIdDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1SessionsIdDetailQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Pauses an active work session with a specified reason. Only active sessions can be paused.
 * @summary Pause work session
 */
export type postApiV1SessionsIdPauseResponse200 = {
	data: Session;
	status: 200;
};

export type postApiV1SessionsIdPauseResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsIdPauseResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsIdPauseResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsIdPauseResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsIdPauseResponseSuccess =
	postApiV1SessionsIdPauseResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsIdPauseResponseError = (
	| postApiV1SessionsIdPauseResponse400
	| postApiV1SessionsIdPauseResponse404
	| postApiV1SessionsIdPauseResponse409
	| postApiV1SessionsIdPauseResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsIdPauseResponse =
	| postApiV1SessionsIdPauseResponseSuccess
	| postApiV1SessionsIdPauseResponseError;

export const getPostApiV1SessionsIdPauseUrl = (id: string) => {
	return `/api/v1/sessions/${id}/pause`;
};

export const postApiV1SessionsIdPause = async (
	id: string,
	postApiV1SessionsIdPauseBody: PostApiV1SessionsIdPauseBody,
	options?: RequestInit,
): Promise<postApiV1SessionsIdPauseResponse> => {
	return customFetch<postApiV1SessionsIdPauseResponse>(
		getPostApiV1SessionsIdPauseUrl(id),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsIdPauseBody),
		},
	);
};

export const getPostApiV1SessionsIdPauseMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsIdPause>>,
		TError,
		{ id: string; data: PostApiV1SessionsIdPauseBody },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsIdPause>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdPauseBody },
	TContext
> => {
	const mutationKey = ["postApiV1SessionsIdPause"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsIdPause>>,
		{ id: string; data: PostApiV1SessionsIdPauseBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiV1SessionsIdPause(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsIdPauseMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1SessionsIdPause>>
>;
export type PostApiV1SessionsIdPauseMutationBody = PostApiV1SessionsIdPauseBody;
export type PostApiV1SessionsIdPauseMutationError = ErrorType<ApiError>;

/**
 * @summary Pause work session
 */
export const usePostApiV1SessionsIdPause = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsIdPause>>,
			TError,
			{ id: string; data: PostApiV1SessionsIdPauseBody },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsIdPause>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdPauseBody },
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsIdPauseMutationOptions(options),
		queryClient,
	);
};
/**
 * Creates a new work session for the same GitHub issue as a terminated session. The new session starts from the clarification stage.
 * @summary Restart work session
 */
export type postApiV1SessionsIdRestartResponse201 = {
	data: Session;
	status: 201;
};

export type postApiV1SessionsIdRestartResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsIdRestartResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsIdRestartResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsIdRestartResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsIdRestartResponseSuccess =
	postApiV1SessionsIdRestartResponse201 & {
		headers: Headers;
	};
export type postApiV1SessionsIdRestartResponseError = (
	| postApiV1SessionsIdRestartResponse400
	| postApiV1SessionsIdRestartResponse404
	| postApiV1SessionsIdRestartResponse409
	| postApiV1SessionsIdRestartResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsIdRestartResponse =
	| postApiV1SessionsIdRestartResponseSuccess
	| postApiV1SessionsIdRestartResponseError;

export const getPostApiV1SessionsIdRestartUrl = (id: string) => {
	return `/api/v1/sessions/${id}/restart`;
};

export const postApiV1SessionsIdRestart = async (
	id: string,
	postApiV1SessionsIdRestartBody: PostApiV1SessionsIdRestartBody,
	options?: RequestInit,
): Promise<postApiV1SessionsIdRestartResponse> => {
	return customFetch<postApiV1SessionsIdRestartResponse>(
		getPostApiV1SessionsIdRestartUrl(id),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsIdRestartBody),
		},
	);
};

export const getPostApiV1SessionsIdRestartMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>,
		TError,
		{ id: string; data: PostApiV1SessionsIdRestartBody },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdRestartBody },
	TContext
> => {
	const mutationKey = ["postApiV1SessionsIdRestart"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>,
		{ id: string; data: PostApiV1SessionsIdRestartBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiV1SessionsIdRestart(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsIdRestartMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>
>;
export type PostApiV1SessionsIdRestartMutationBody =
	PostApiV1SessionsIdRestartBody;
export type PostApiV1SessionsIdRestartMutationError = ErrorType<ApiError>;

/**
 * @summary Restart work session
 */
export const usePostApiV1SessionsIdRestart = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>,
			TError,
			{ id: string; data: PostApiV1SessionsIdRestartBody },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsIdRestart>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdRestartBody },
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsIdRestartMutationOptions(options),
		queryClient,
	);
};
/**
 * Resumes a paused work session. Only paused sessions can be resumed.
 * @summary Resume work session
 */
export type postApiV1SessionsIdResumeResponse200 = {
	data: Session;
	status: 200;
};

export type postApiV1SessionsIdResumeResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsIdResumeResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsIdResumeResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsIdResumeResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsIdResumeResponseSuccess =
	postApiV1SessionsIdResumeResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsIdResumeResponseError = (
	| postApiV1SessionsIdResumeResponse400
	| postApiV1SessionsIdResumeResponse404
	| postApiV1SessionsIdResumeResponse409
	| postApiV1SessionsIdResumeResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsIdResumeResponse =
	| postApiV1SessionsIdResumeResponseSuccess
	| postApiV1SessionsIdResumeResponseError;

export const getPostApiV1SessionsIdResumeUrl = (id: string) => {
	return `/api/v1/sessions/${id}/resume`;
};

export const postApiV1SessionsIdResume = async (
	id: string,
	postApiV1SessionsIdResumeBody: PostApiV1SessionsIdResumeBody,
	options?: RequestInit,
): Promise<postApiV1SessionsIdResumeResponse> => {
	return customFetch<postApiV1SessionsIdResumeResponse>(
		getPostApiV1SessionsIdResumeUrl(id),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsIdResumeBody),
		},
	);
};

export const getPostApiV1SessionsIdResumeMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsIdResume>>,
		TError,
		{ id: string; data: PostApiV1SessionsIdResumeBody },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsIdResume>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdResumeBody },
	TContext
> => {
	const mutationKey = ["postApiV1SessionsIdResume"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsIdResume>>,
		{ id: string; data: PostApiV1SessionsIdResumeBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiV1SessionsIdResume(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsIdResumeMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1SessionsIdResume>>
>;
export type PostApiV1SessionsIdResumeMutationBody =
	PostApiV1SessionsIdResumeBody;
export type PostApiV1SessionsIdResumeMutationError = ErrorType<ApiError>;

/**
 * @summary Resume work session
 */
export const usePostApiV1SessionsIdResume = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsIdResume>>,
			TError,
			{ id: string; data: PostApiV1SessionsIdResumeBody },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsIdResume>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdResumeBody },
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsIdResumeMutationOptions(options),
		queryClient,
	);
};
/**
 * Rolls back a work session to a specified previous stage (clarification, design, or task_breakdown). Only active sessions can be rolled back.
 * @summary Rollback work session
 */
export type postApiV1SessionsIdRollbackResponse200 = {
	data: Session;
	status: 200;
};

export type postApiV1SessionsIdRollbackResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsIdRollbackResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsIdRollbackResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsIdRollbackResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsIdRollbackResponseSuccess =
	postApiV1SessionsIdRollbackResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsIdRollbackResponseError = (
	| postApiV1SessionsIdRollbackResponse400
	| postApiV1SessionsIdRollbackResponse404
	| postApiV1SessionsIdRollbackResponse409
	| postApiV1SessionsIdRollbackResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsIdRollbackResponse =
	| postApiV1SessionsIdRollbackResponseSuccess
	| postApiV1SessionsIdRollbackResponseError;

export const getPostApiV1SessionsIdRollbackUrl = (id: string) => {
	return `/api/v1/sessions/${id}/rollback`;
};

export const postApiV1SessionsIdRollback = async (
	id: string,
	postApiV1SessionsIdRollbackBody: PostApiV1SessionsIdRollbackBody,
	options?: RequestInit,
): Promise<postApiV1SessionsIdRollbackResponse> => {
	return customFetch<postApiV1SessionsIdRollbackResponse>(
		getPostApiV1SessionsIdRollbackUrl(id),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsIdRollbackBody),
		},
	);
};

export const getPostApiV1SessionsIdRollbackMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>,
		TError,
		{ id: string; data: PostApiV1SessionsIdRollbackBody },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdRollbackBody },
	TContext
> => {
	const mutationKey = ["postApiV1SessionsIdRollback"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>,
		{ id: string; data: PostApiV1SessionsIdRollbackBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiV1SessionsIdRollback(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsIdRollbackMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>
>;
export type PostApiV1SessionsIdRollbackMutationBody =
	PostApiV1SessionsIdRollbackBody;
export type PostApiV1SessionsIdRollbackMutationError = ErrorType<ApiError>;

/**
 * @summary Rollback work session
 */
export const usePostApiV1SessionsIdRollback = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>,
			TError,
			{ id: string; data: PostApiV1SessionsIdRollbackBody },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsIdRollback>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdRollbackBody },
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsIdRollbackMutationOptions(options),
		queryClient,
	);
};
/**
 * Terminates a work session permanently. Active or paused sessions can be terminated.
 * @summary Terminate work session
 */
export type postApiV1SessionsIdTerminateResponse200 = {
	data: Session;
	status: 200;
};

export type postApiV1SessionsIdTerminateResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsIdTerminateResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsIdTerminateResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsIdTerminateResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsIdTerminateResponseSuccess =
	postApiV1SessionsIdTerminateResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsIdTerminateResponseError = (
	| postApiV1SessionsIdTerminateResponse400
	| postApiV1SessionsIdTerminateResponse404
	| postApiV1SessionsIdTerminateResponse409
	| postApiV1SessionsIdTerminateResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsIdTerminateResponse =
	| postApiV1SessionsIdTerminateResponseSuccess
	| postApiV1SessionsIdTerminateResponseError;

export const getPostApiV1SessionsIdTerminateUrl = (id: string) => {
	return `/api/v1/sessions/${id}/terminate`;
};

export const postApiV1SessionsIdTerminate = async (
	id: string,
	postApiV1SessionsIdTerminateBody: PostApiV1SessionsIdTerminateBody,
	options?: RequestInit,
): Promise<postApiV1SessionsIdTerminateResponse> => {
	return customFetch<postApiV1SessionsIdTerminateResponse>(
		getPostApiV1SessionsIdTerminateUrl(id),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsIdTerminateBody),
		},
	);
};

export const getPostApiV1SessionsIdTerminateMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>,
		TError,
		{ id: string; data: PostApiV1SessionsIdTerminateBody },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdTerminateBody },
	TContext
> => {
	const mutationKey = ["postApiV1SessionsIdTerminate"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>,
		{ id: string; data: PostApiV1SessionsIdTerminateBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return postApiV1SessionsIdTerminate(id, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsIdTerminateMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>
>;
export type PostApiV1SessionsIdTerminateMutationBody =
	PostApiV1SessionsIdTerminateBody;
export type PostApiV1SessionsIdTerminateMutationError = ErrorType<ApiError>;

/**
 * @summary Terminate work session
 */
export const usePostApiV1SessionsIdTerminate = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>,
			TError,
			{ id: string; data: PostApiV1SessionsIdTerminateBody },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsIdTerminate>>,
	TError,
	{ id: string; data: PostApiV1SessionsIdTerminateBody },
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsIdTerminateMutationOptions(options),
		queryClient,
	);
};
