/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type {
	GetApiV1HealthBody,
	GetApiV1HealthDetailBody,
	GetHealthBody,
	HealthCheck,
	HealthDetail,
} from "../schemas";

/**
 * Returns the basic API health status and version
 * @summary API health check
 */
export type getApiV1HealthResponse200 = {
	data: HealthCheck;
	status: 200;
};

export type getApiV1HealthResponseSuccess = getApiV1HealthResponse200 & {
	headers: Headers;
};

export type getApiV1HealthResponse = getApiV1HealthResponseSuccess;

export const getGetApiV1HealthUrl = () => {
	return `/api/v1/health`;
};

export const getApiV1Health = async (
	getApiV1HealthBody: GetApiV1HealthBody,
	options?: RequestInit,
): Promise<getApiV1HealthResponse> => {
	const res = await fetch(getGetApiV1HealthUrl(), {
		...options,
		method: "GET",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getApiV1HealthBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1HealthResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1HealthResponse;
};

export const getGetApiV1HealthQueryKey = (
	getApiV1HealthBody?: GetApiV1HealthBody,
) => {
	return [`/api/v1/health`, getApiV1HealthBody] as const;
};

export const getGetApiV1HealthQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = unknown,
>(
	getApiV1HealthBody: GetApiV1HealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1HealthQueryKey(getApiV1HealthBody);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({
		signal,
	}) => getApiV1Health(getApiV1HealthBody, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Health>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1HealthQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Health>>
>;
export type GetApiV1HealthQueryError = unknown;

export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = unknown,
>(
	getApiV1HealthBody: GetApiV1HealthBody,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Health>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Health>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = unknown,
>(
	getApiV1HealthBody: GetApiV1HealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Health>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Health>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = unknown,
>(
	getApiV1HealthBody: GetApiV1HealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary API health check
 */

export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = unknown,
>(
	getApiV1HealthBody: GetApiV1HealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1HealthQueryOptions(
		getApiV1HealthBody,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns detailed health status including database, GitHub, and Git checks
 * @summary Detailed health check
 */
export type getApiV1HealthDetailResponse200 = {
	data: HealthDetail;
	status: 200;
};

export type getApiV1HealthDetailResponseSuccess =
	getApiV1HealthDetailResponse200 & {
		headers: Headers;
	};

export type getApiV1HealthDetailResponse = getApiV1HealthDetailResponseSuccess;

export const getGetApiV1HealthDetailUrl = () => {
	return `/api/v1/health/detail`;
};

export const getApiV1HealthDetail = async (
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options?: RequestInit,
): Promise<getApiV1HealthDetailResponse> => {
	const res = await fetch(getGetApiV1HealthDetailUrl(), {
		...options,
		method: "GET",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getApiV1HealthDetailBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1HealthDetailResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1HealthDetailResponse;
};

export const getGetApiV1HealthDetailQueryKey = (
	getApiV1HealthDetailBody?: GetApiV1HealthDetailBody,
) => {
	return [`/api/v1/health/detail`, getApiV1HealthDetailBody] as const;
};

export const getGetApiV1HealthDetailQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = unknown,
>(
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1HealthDetailQueryKey(getApiV1HealthDetailBody);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1HealthDetail>>
	> = ({ signal }) =>
		getApiV1HealthDetail(getApiV1HealthDetailBody, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1HealthDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1HealthDetailQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1HealthDetail>>
>;
export type GetApiV1HealthDetailQueryError = unknown;

export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = unknown,
>(
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1HealthDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1HealthDetail>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = unknown,
>(
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1HealthDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1HealthDetail>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = unknown,
>(
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detailed health check
 */

export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = unknown,
>(
	getApiV1HealthDetailBody: GetApiV1HealthDetailBody,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1HealthDetailQueryOptions(
		getApiV1HealthDetailBody,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the server health status and version (legacy endpoint)
 * @summary Basic health check
 */
export type getHealthResponse200 = {
	data: HealthCheck;
	status: 200;
};

export type getHealthResponseSuccess = getHealthResponse200 & {
	headers: Headers;
};

export type getHealthResponse = getHealthResponseSuccess;

export const getGetHealthUrl = () => {
	return `/health`;
};

export const getHealth = async (
	getHealthBody: GetHealthBody,
	options?: RequestInit,
): Promise<getHealthResponse> => {
	const res = await fetch(getGetHealthUrl(), {
		...options,
		method: "GET",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getHealthBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getHealthResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getHealthResponse;
};

export const getGetHealthQueryKey = (getHealthBody?: GetHealthBody) => {
	return [`/health`, getHealthBody] as const;
};

export const getGetHealthQueryOptions = <
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = unknown,
>(
	getHealthBody: GetHealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetHealthQueryKey(getHealthBody);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({
		signal,
	}) => getHealth(getHealthBody, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getHealth>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealthQueryResult = NonNullable<
	Awaited<ReturnType<typeof getHealth>>
>;
export type GetHealthQueryError = unknown;

export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = unknown,
>(
	getHealthBody: GetHealthBody,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getHealth>>,
					TError,
					Awaited<ReturnType<typeof getHealth>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = unknown,
>(
	getHealthBody: GetHealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getHealth>>,
					TError,
					Awaited<ReturnType<typeof getHealth>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = unknown,
>(
	getHealthBody: GetHealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Basic health check
 */

export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = unknown,
>(
	getHealthBody: GetHealthBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetHealthQueryOptions(getHealthBody, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
