/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../../lib/custom-fetch";

import { customFetch } from "../../lib/custom-fetch";
import type { HealthCheck, HealthDetail } from "../schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns the basic API health status and version
 * @summary API health check
 */
export type getApiV1HealthResponse200 = {
	data: HealthCheck;
	status: 200;
};

export type getApiV1HealthResponseSuccess = getApiV1HealthResponse200 & {
	headers: Headers;
};

export type getApiV1HealthResponse = getApiV1HealthResponseSuccess;

export const getGetApiV1HealthUrl = () => {
	return `/api/v1/health`;
};

export const getApiV1Health = async (
	options?: RequestInit,
): Promise<getApiV1HealthResponse> => {
	return customFetch<getApiV1HealthResponse>(getGetApiV1HealthUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetApiV1HealthQueryKey = () => {
	return [`/api/v1/health`] as const;
};

export const getGetApiV1HealthQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1HealthQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Health>>> = ({
		signal,
	}) => getApiV1Health({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Health>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1HealthQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Health>>
>;
export type GetApiV1HealthQueryError = ErrorType<unknown>;

export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Health>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Health>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Health>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Health>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary API health check
 */

export function useGetApiV1Health<
	TData = Awaited<ReturnType<typeof getApiV1Health>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Health>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1HealthQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns detailed health status including database, GitHub, and Git checks
 * @summary Detailed health check
 */
export type getApiV1HealthDetailResponse200 = {
	data: HealthDetail;
	status: 200;
};

export type getApiV1HealthDetailResponseSuccess =
	getApiV1HealthDetailResponse200 & {
		headers: Headers;
	};

export type getApiV1HealthDetailResponse = getApiV1HealthDetailResponseSuccess;

export const getGetApiV1HealthDetailUrl = () => {
	return `/api/v1/health/detail`;
};

export const getApiV1HealthDetail = async (
	options?: RequestInit,
): Promise<getApiV1HealthDetailResponse> => {
	return customFetch<getApiV1HealthDetailResponse>(
		getGetApiV1HealthDetailUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetApiV1HealthDetailQueryKey = () => {
	return [`/api/v1/health/detail`] as const;
};

export const getGetApiV1HealthDetailQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiV1HealthDetail>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1HealthDetailQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1HealthDetail>>
	> = ({ signal }) => getApiV1HealthDetail({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1HealthDetail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1HealthDetailQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1HealthDetail>>
>;
export type GetApiV1HealthDetailQueryError = ErrorType<unknown>;

export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1HealthDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1HealthDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1HealthDetail>>,
					TError,
					Awaited<ReturnType<typeof getApiV1HealthDetail>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detailed health check
 */

export function useGetApiV1HealthDetail<
	TData = Awaited<ReturnType<typeof getApiV1HealthDetail>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1HealthDetail>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1HealthDetailQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Returns the server health status and version (legacy endpoint)
 * @summary Basic health check
 */
export type getHealthResponse200 = {
	data: HealthCheck;
	status: 200;
};

export type getHealthResponseSuccess = getHealthResponse200 & {
	headers: Headers;
};

export type getHealthResponse = getHealthResponseSuccess;

export const getGetHealthUrl = () => {
	return `/health`;
};

export const getHealth = async (
	options?: RequestInit,
): Promise<getHealthResponse> => {
	return customFetch<getHealthResponse>(getGetHealthUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetHealthQueryKey = () => {
	return [`/health`] as const;
};

export const getGetHealthQueryOptions = <
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetHealthQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({
		signal,
	}) => getHealth({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getHealth>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHealthQueryResult = NonNullable<
	Awaited<ReturnType<typeof getHealth>>
>;
export type GetHealthQueryError = ErrorType<unknown>;

export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getHealth>>,
					TError,
					Awaited<ReturnType<typeof getHealth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getHealth>>,
					TError,
					Awaited<ReturnType<typeof getHealth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Basic health check
 */

export function useGetHealth<
	TData = Awaited<ReturnType<typeof getHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetHealthQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
