/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ApiError,
	GetApiV1UsersParams,
	GithubComRyuybLitchiInternalApplicationServerHandlerUserUserListResponse,
	GithubComRyuybLitchiInternalApplicationServerHandlerUserUserResponse,
	PostApiV1UsersBody,
	PutApiV1UsersIdBody,
} from "../schemas";

/**
 * Retrieves a paginated list of users (admin only)
 * @summary List users
 */
export type getApiV1UsersResponse200 = {
	data: GithubComRyuybLitchiInternalApplicationServerHandlerUserUserListResponse;
	status: 200;
};

export type getApiV1UsersResponse401 = {
	data: ApiError;
	status: 401;
};

export type getApiV1UsersResponse403 = {
	data: ApiError;
	status: 403;
};

export type getApiV1UsersResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1UsersResponseSuccess = getApiV1UsersResponse200 & {
	headers: Headers;
};
export type getApiV1UsersResponseError = (
	| getApiV1UsersResponse401
	| getApiV1UsersResponse403
	| getApiV1UsersResponse500
) & {
	headers: Headers;
};

export type getApiV1UsersResponse =
	| getApiV1UsersResponseSuccess
	| getApiV1UsersResponseError;

export const getGetApiV1UsersUrl = (params?: GetApiV1UsersParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/users?${stringifiedParams}`
		: `/api/v1/users`;
};

export const getApiV1Users = async (
	params?: GetApiV1UsersParams,
	options?: RequestInit,
): Promise<getApiV1UsersResponse> => {
	const res = await fetch(getGetApiV1UsersUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1UsersResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1UsersResponse;
};

export const getGetApiV1UsersQueryKey = (params?: GetApiV1UsersParams) => {
	return [`/api/v1/users`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1UsersQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Users>>,
	TError = ApiError,
>(
	params?: GetApiV1UsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Users>>> = ({
		signal,
	}) => getApiV1Users(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Users>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1UsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Users>>
>;
export type GetApiV1UsersQueryError = ApiError;

export function useGetApiV1Users<
	TData = Awaited<ReturnType<typeof getApiV1Users>>,
	TError = ApiError,
>(
	params: undefined | GetApiV1UsersParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Users>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Users>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Users<
	TData = Awaited<ReturnType<typeof getApiV1Users>>,
	TError = ApiError,
>(
	params?: GetApiV1UsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Users>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Users>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Users<
	TData = Awaited<ReturnType<typeof getApiV1Users>>,
	TError = ApiError,
>(
	params?: GetApiV1UsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List users
 */

export function useGetApiV1Users<
	TData = Awaited<ReturnType<typeof getApiV1Users>>,
	TError = ApiError,
>(
	params?: GetApiV1UsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Users>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1UsersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Creates a new user (admin only)
 * @summary Create user
 */
export type postApiV1UsersResponse201 = {
	data: GithubComRyuybLitchiInternalApplicationServerHandlerUserUserResponse;
	status: 201;
};

export type postApiV1UsersResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1UsersResponse401 = {
	data: ApiError;
	status: 401;
};

export type postApiV1UsersResponse403 = {
	data: ApiError;
	status: 403;
};

export type postApiV1UsersResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1UsersResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1UsersResponseSuccess = postApiV1UsersResponse201 & {
	headers: Headers;
};
export type postApiV1UsersResponseError = (
	| postApiV1UsersResponse400
	| postApiV1UsersResponse401
	| postApiV1UsersResponse403
	| postApiV1UsersResponse409
	| postApiV1UsersResponse500
) & {
	headers: Headers;
};

export type postApiV1UsersResponse =
	| postApiV1UsersResponseSuccess
	| postApiV1UsersResponseError;

export const getPostApiV1UsersUrl = () => {
	return `/api/v1/users`;
};

export const postApiV1Users = async (
	postApiV1UsersBody: PostApiV1UsersBody,
	options?: RequestInit,
): Promise<postApiV1UsersResponse> => {
	const res = await fetch(getPostApiV1UsersUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(postApiV1UsersBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1UsersResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1UsersResponse;
};

export const getPostApiV1UsersMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1Users>>,
		TError,
		{ data: PostApiV1UsersBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1Users>>,
	TError,
	{ data: PostApiV1UsersBody },
	TContext
> => {
	const mutationKey = ["postApiV1Users"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1Users>>,
		{ data: PostApiV1UsersBody }
	> = (props) => {
		const { data } = props ?? {};

		return postApiV1Users(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1UsersMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1Users>>
>;
export type PostApiV1UsersMutationBody = PostApiV1UsersBody;
export type PostApiV1UsersMutationError = ApiError;

/**
 * @summary Create user
 */
export const usePostApiV1Users = <TError = ApiError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1Users>>,
			TError,
			{ data: PostApiV1UsersBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1Users>>,
	TError,
	{ data: PostApiV1UsersBody },
	TContext
> => {
	return useMutation(getPostApiV1UsersMutationOptions(options), queryClient);
};
/**
 * Deletes a user (admin only)
 * @summary Delete user
 */
export type deleteApiV1UsersIdResponse204 = {
	data: void;
	status: 204;
};

export type deleteApiV1UsersIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type deleteApiV1UsersIdResponse401 = {
	data: ApiError;
	status: 401;
};

export type deleteApiV1UsersIdResponse403 = {
	data: ApiError;
	status: 403;
};

export type deleteApiV1UsersIdResponse404 = {
	data: ApiError;
	status: 404;
};

export type deleteApiV1UsersIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type deleteApiV1UsersIdResponseSuccess =
	deleteApiV1UsersIdResponse204 & {
		headers: Headers;
	};
export type deleteApiV1UsersIdResponseError = (
	| deleteApiV1UsersIdResponse400
	| deleteApiV1UsersIdResponse401
	| deleteApiV1UsersIdResponse403
	| deleteApiV1UsersIdResponse404
	| deleteApiV1UsersIdResponse500
) & {
	headers: Headers;
};

export type deleteApiV1UsersIdResponse =
	| deleteApiV1UsersIdResponseSuccess
	| deleteApiV1UsersIdResponseError;

export const getDeleteApiV1UsersIdUrl = (id: string) => {
	return `/api/v1/users/${id}`;
};

export const deleteApiV1UsersId = async (
	id: string,
	options?: RequestInit,
): Promise<deleteApiV1UsersIdResponse> => {
	const res = await fetch(getDeleteApiV1UsersIdUrl(id), {
		...options,
		method: "DELETE",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteApiV1UsersIdResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteApiV1UsersIdResponse;
};

export const getDeleteApiV1UsersIdMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiV1UsersId>>,
		TError,
		{ id: string },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiV1UsersId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteApiV1UsersId"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiV1UsersId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteApiV1UsersId(id, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1UsersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1UsersId>>
>;

export type DeleteApiV1UsersIdMutationError = ApiError;

/**
 * @summary Delete user
 */
export const useDeleteApiV1UsersId = <TError = ApiError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiV1UsersId>>,
			TError,
			{ id: string },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiV1UsersId>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getDeleteApiV1UsersIdMutationOptions(options),
		queryClient,
	);
};
/**
 * Updates an existing user (admin only)
 * @summary Update user
 */
export type putApiV1UsersIdResponse200 = {
	data: GithubComRyuybLitchiInternalApplicationServerHandlerUserUserResponse;
	status: 200;
};

export type putApiV1UsersIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type putApiV1UsersIdResponse401 = {
	data: ApiError;
	status: 401;
};

export type putApiV1UsersIdResponse403 = {
	data: ApiError;
	status: 403;
};

export type putApiV1UsersIdResponse404 = {
	data: ApiError;
	status: 404;
};

export type putApiV1UsersIdResponse409 = {
	data: ApiError;
	status: 409;
};

export type putApiV1UsersIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type putApiV1UsersIdResponseSuccess = putApiV1UsersIdResponse200 & {
	headers: Headers;
};
export type putApiV1UsersIdResponseError = (
	| putApiV1UsersIdResponse400
	| putApiV1UsersIdResponse401
	| putApiV1UsersIdResponse403
	| putApiV1UsersIdResponse404
	| putApiV1UsersIdResponse409
	| putApiV1UsersIdResponse500
) & {
	headers: Headers;
};

export type putApiV1UsersIdResponse =
	| putApiV1UsersIdResponseSuccess
	| putApiV1UsersIdResponseError;

export const getPutApiV1UsersIdUrl = (id: string) => {
	return `/api/v1/users/${id}`;
};

export const putApiV1UsersId = async (
	id: string,
	putApiV1UsersIdBody: PutApiV1UsersIdBody,
	options?: RequestInit,
): Promise<putApiV1UsersIdResponse> => {
	const res = await fetch(getPutApiV1UsersIdUrl(id), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(putApiV1UsersIdBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: putApiV1UsersIdResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as putApiV1UsersIdResponse;
};

export const getPutApiV1UsersIdMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiV1UsersId>>,
		TError,
		{ id: string; data: PutApiV1UsersIdBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiV1UsersId>>,
	TError,
	{ id: string; data: PutApiV1UsersIdBody },
	TContext
> => {
	const mutationKey = ["putApiV1UsersId"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiV1UsersId>>,
		{ id: string; data: PutApiV1UsersIdBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return putApiV1UsersId(id, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiV1UsersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiV1UsersId>>
>;
export type PutApiV1UsersIdMutationBody = PutApiV1UsersIdBody;
export type PutApiV1UsersIdMutationError = ApiError;

/**
 * @summary Update user
 */
export const usePutApiV1UsersId = <TError = ApiError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiV1UsersId>>,
			TError,
			{ id: string; data: PutApiV1UsersIdBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiV1UsersId>>,
	TError,
	{ id: string; data: PutApiV1UsersIdBody },
	TContext
> => {
	return useMutation(getPutApiV1UsersIdMutationOptions(options), queryClient);
};
