// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/ryuyb/litchi/internal/domain/aggregate"
	"github.com/ryuyb/litchi/internal/domain/entity"
	"github.com/ryuyb/litchi/internal/domain/event"
	"github.com/ryuyb/litchi/internal/domain/valueobject"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentRunner creates a new instance of MockAgentRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRunner {
	mock := &MockAgentRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentRunner is an autogenerated mock type for the AgentRunner type
type MockAgentRunner struct {
	mock.Mock
}

type MockAgentRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRunner) EXPECT() *MockAgentRunner_Expecter {
	return &MockAgentRunner_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) Cancel(sessionID uuid.UUID) error {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRunner_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockAgentRunner_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - sessionID uuid.UUID
func (_e *MockAgentRunner_Expecter) Cancel(sessionID interface{}) *MockAgentRunner_Cancel_Call {
	return &MockAgentRunner_Cancel_Call{Call: _e.mock.On("Cancel", sessionID)}
}

func (_c *MockAgentRunner_Cancel_Call) Run(run func(sessionID uuid.UUID)) *MockAgentRunner_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRunner_Cancel_Call) Return(err error) *MockAgentRunner_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRunner_Cancel_Call) RunAndReturn(run func(sessionID uuid.UUID) error) *MockAgentRunner_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) Execute(ctx context.Context, req *AgentRequest) (*AgentResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *AgentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AgentRequest) (*AgentResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AgentRequest) *AgentResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AgentRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRunner_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAgentRunner_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req *AgentRequest
func (_e *MockAgentRunner_Expecter) Execute(ctx interface{}, req interface{}) *MockAgentRunner_Execute_Call {
	return &MockAgentRunner_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockAgentRunner_Execute_Call) Run(run func(ctx context.Context, req *AgentRequest)) *MockAgentRunner_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AgentRequest
		if args[1] != nil {
			arg1 = args[1].(*AgentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRunner_Execute_Call) Return(agentResponse *AgentResponse, err error) *MockAgentRunner_Execute_Call {
	_c.Call.Return(agentResponse, err)
	return _c
}

func (_c *MockAgentRunner_Execute_Call) RunAndReturn(run func(ctx context.Context, req *AgentRequest) (*AgentResponse, error)) *MockAgentRunner_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteWithRetry provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) ExecuteWithRetry(ctx context.Context, req *AgentRequest, policy valueobject.RetryPolicy) (*AgentResponse, error) {
	ret := _mock.Called(ctx, req, policy)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteWithRetry")
	}

	var r0 *AgentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AgentRequest, valueobject.RetryPolicy) (*AgentResponse, error)); ok {
		return returnFunc(ctx, req, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AgentRequest, valueobject.RetryPolicy) *AgentResponse); ok {
		r0 = returnFunc(ctx, req, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AgentRequest, valueobject.RetryPolicy) error); ok {
		r1 = returnFunc(ctx, req, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRunner_ExecuteWithRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteWithRetry'
type MockAgentRunner_ExecuteWithRetry_Call struct {
	*mock.Call
}

// ExecuteWithRetry is a helper method to define mock.On call
//   - ctx context.Context
//   - req *AgentRequest
//   - policy valueobject.RetryPolicy
func (_e *MockAgentRunner_Expecter) ExecuteWithRetry(ctx interface{}, req interface{}, policy interface{}) *MockAgentRunner_ExecuteWithRetry_Call {
	return &MockAgentRunner_ExecuteWithRetry_Call{Call: _e.mock.On("ExecuteWithRetry", ctx, req, policy)}
}

func (_c *MockAgentRunner_ExecuteWithRetry_Call) Run(run func(ctx context.Context, req *AgentRequest, policy valueobject.RetryPolicy)) *MockAgentRunner_ExecuteWithRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AgentRequest
		if args[1] != nil {
			arg1 = args[1].(*AgentRequest)
		}
		var arg2 valueobject.RetryPolicy
		if args[2] != nil {
			arg2 = args[2].(valueobject.RetryPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRunner_ExecuteWithRetry_Call) Return(agentResponse *AgentResponse, err error) *MockAgentRunner_ExecuteWithRetry_Call {
	_c.Call.Return(agentResponse, err)
	return _c
}

func (_c *MockAgentRunner_ExecuteWithRetry_Call) RunAndReturn(run func(ctx context.Context, req *AgentRequest, policy valueobject.RetryPolicy) (*AgentResponse, error)) *MockAgentRunner_ExecuteWithRetry_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) GetStatus(sessionID uuid.UUID) (*AgentStatus, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *AgentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*AgentStatus, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *AgentStatus); ok {
		r0 = returnFunc(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRunner_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockAgentRunner_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - sessionID uuid.UUID
func (_e *MockAgentRunner_Expecter) GetStatus(sessionID interface{}) *MockAgentRunner_GetStatus_Call {
	return &MockAgentRunner_GetStatus_Call{Call: _e.mock.On("GetStatus", sessionID)}
}

func (_c *MockAgentRunner_GetStatus_Call) Run(run func(sessionID uuid.UUID)) *MockAgentRunner_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRunner_GetStatus_Call) Return(agentStatus *AgentStatus, err error) *MockAgentRunner_GetStatus_Call {
	_c.Call.Return(agentStatus, err)
	return _c
}

func (_c *MockAgentRunner_GetStatus_Call) RunAndReturn(run func(sessionID uuid.UUID) (*AgentStatus, error)) *MockAgentRunner_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) IsRunning(sessionID uuid.UUID) bool {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgentRunner_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockAgentRunner_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
//   - sessionID uuid.UUID
func (_e *MockAgentRunner_Expecter) IsRunning(sessionID interface{}) *MockAgentRunner_IsRunning_Call {
	return &MockAgentRunner_IsRunning_Call{Call: _e.mock.On("IsRunning", sessionID)}
}

func (_c *MockAgentRunner_IsRunning_Call) Run(run func(sessionID uuid.UUID)) *MockAgentRunner_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRunner_IsRunning_Call) Return(b bool) *MockAgentRunner_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgentRunner_IsRunning_Call) RunAndReturn(run func(sessionID uuid.UUID) bool) *MockAgentRunner_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) PrepareContext(ctx context.Context, sessionID uuid.UUID, worktreePath string) (*AgentContext, error) {
	ret := _mock.Called(ctx, sessionID, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *AgentContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*AgentContext, error)); ok {
		return returnFunc(ctx, sessionID, worktreePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *AgentContext); ok {
		r0 = returnFunc(ctx, sessionID, worktreePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AgentContext)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, sessionID, worktreePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRunner_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockAgentRunner_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - worktreePath string
func (_e *MockAgentRunner_Expecter) PrepareContext(ctx interface{}, sessionID interface{}, worktreePath interface{}) *MockAgentRunner_PrepareContext_Call {
	return &MockAgentRunner_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, sessionID, worktreePath)}
}

func (_c *MockAgentRunner_PrepareContext_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, worktreePath string)) *MockAgentRunner_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRunner_PrepareContext_Call) Return(agentContext *AgentContext, err error) *MockAgentRunner_PrepareContext_Call {
	_c.Call.Return(agentContext, err)
	return _c
}

func (_c *MockAgentRunner_PrepareContext_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, worktreePath string) (*AgentContext, error)) *MockAgentRunner_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// SaveContext provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) SaveContext(ctx context.Context, worktreePath string, cache *AgentContextCache) error {
	ret := _mock.Called(ctx, worktreePath, cache)

	if len(ret) == 0 {
		panic("no return value specified for SaveContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *AgentContextCache) error); ok {
		r0 = returnFunc(ctx, worktreePath, cache)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRunner_SaveContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveContext'
type MockAgentRunner_SaveContext_Call struct {
	*mock.Call
}

// SaveContext is a helper method to define mock.On call
//   - ctx context.Context
//   - worktreePath string
//   - cache *AgentContextCache
func (_e *MockAgentRunner_Expecter) SaveContext(ctx interface{}, worktreePath interface{}, cache interface{}) *MockAgentRunner_SaveContext_Call {
	return &MockAgentRunner_SaveContext_Call{Call: _e.mock.On("SaveContext", ctx, worktreePath, cache)}
}

func (_c *MockAgentRunner_SaveContext_Call) Run(run func(ctx context.Context, worktreePath string, cache *AgentContextCache)) *MockAgentRunner_SaveContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *AgentContextCache
		if args[2] != nil {
			arg2 = args[2].(*AgentContextCache)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRunner_SaveContext_Call) Return(err error) *MockAgentRunner_SaveContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRunner_SaveContext_Call) RunAndReturn(run func(ctx context.Context, worktreePath string, cache *AgentContextCache) error) *MockAgentRunner_SaveContext_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRunner_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockAgentRunner_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentRunner_Expecter) Shutdown(ctx interface{}) *MockAgentRunner_Shutdown_Call {
	return &MockAgentRunner_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockAgentRunner_Shutdown_Call) Run(run func(ctx context.Context)) *MockAgentRunner_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRunner_Shutdown_Call) Return(err error) *MockAgentRunner_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRunner_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockAgentRunner_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRequest provides a mock function for the type MockAgentRunner
func (_mock *MockAgentRunner) ValidateRequest(req *AgentRequest) error {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*AgentRequest) error); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRunner_ValidateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRequest'
type MockAgentRunner_ValidateRequest_Call struct {
	*mock.Call
}

// ValidateRequest is a helper method to define mock.On call
//   - req *AgentRequest
func (_e *MockAgentRunner_Expecter) ValidateRequest(req interface{}) *MockAgentRunner_ValidateRequest_Call {
	return &MockAgentRunner_ValidateRequest_Call{Call: _e.mock.On("ValidateRequest", req)}
}

func (_c *MockAgentRunner_ValidateRequest_Call) Run(run func(req *AgentRequest)) *MockAgentRunner_ValidateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *AgentRequest
		if args[0] != nil {
			arg0 = args[0].(*AgentRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRunner_ValidateRequest_Call) Return(err error) *MockAgentRunner_ValidateRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRunner_ValidateRequest_Call) RunAndReturn(run func(req *AgentRequest) error) *MockAgentRunner_ValidateRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventDispatcher creates a new instance of MockEventDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventDispatcher {
	mock := &MockEventDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventDispatcher is an autogenerated mock type for the EventDispatcher type
type MockEventDispatcher struct {
	mock.Mock
}

type MockEventDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventDispatcher) EXPECT() *MockEventDispatcher_Expecter {
	return &MockEventDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) Dispatch(event1 event.DomainEvent) {
	_mock.Called(event1)
	return
}

// MockEventDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockEventDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - event1 event.DomainEvent
func (_e *MockEventDispatcher_Expecter) Dispatch(event1 interface{}) *MockEventDispatcher_Dispatch_Call {
	return &MockEventDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", event1)}
}

func (_c *MockEventDispatcher_Dispatch_Call) Run(run func(event1 event.DomainEvent)) *MockEventDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 event.DomainEvent
		if args[0] != nil {
			arg0 = args[0].(event.DomainEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_Dispatch_Call) Return() *MockEventDispatcher_Dispatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventDispatcher_Dispatch_Call) RunAndReturn(run func(event1 event.DomainEvent)) *MockEventDispatcher_Dispatch_Call {
	_c.Run(run)
	return _c
}

// DispatchBatch provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) DispatchBatch(events []event.DomainEvent) {
	_mock.Called(events)
	return
}

// MockEventDispatcher_DispatchBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchBatch'
type MockEventDispatcher_DispatchBatch_Call struct {
	*mock.Call
}

// DispatchBatch is a helper method to define mock.On call
//   - events []event.DomainEvent
func (_e *MockEventDispatcher_Expecter) DispatchBatch(events interface{}) *MockEventDispatcher_DispatchBatch_Call {
	return &MockEventDispatcher_DispatchBatch_Call{Call: _e.mock.On("DispatchBatch", events)}
}

func (_c *MockEventDispatcher_DispatchBatch_Call) Run(run func(events []event.DomainEvent)) *MockEventDispatcher_DispatchBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []event.DomainEvent
		if args[0] != nil {
			arg0 = args[0].([]event.DomainEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_DispatchBatch_Call) Return() *MockEventDispatcher_DispatchBatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventDispatcher_DispatchBatch_Call) RunAndReturn(run func(events []event.DomainEvent)) *MockEventDispatcher_DispatchBatch_Call {
	_c.Run(run)
	return _c
}

// RegisterGlobalHandler provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) RegisterGlobalHandler(handler EventHandler) {
	_mock.Called(handler)
	return
}

// MockEventDispatcher_RegisterGlobalHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterGlobalHandler'
type MockEventDispatcher_RegisterGlobalHandler_Call struct {
	*mock.Call
}

// RegisterGlobalHandler is a helper method to define mock.On call
//   - handler EventHandler
func (_e *MockEventDispatcher_Expecter) RegisterGlobalHandler(handler interface{}) *MockEventDispatcher_RegisterGlobalHandler_Call {
	return &MockEventDispatcher_RegisterGlobalHandler_Call{Call: _e.mock.On("RegisterGlobalHandler", handler)}
}

func (_c *MockEventDispatcher_RegisterGlobalHandler_Call) Run(run func(handler EventHandler)) *MockEventDispatcher_RegisterGlobalHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 EventHandler
		if args[0] != nil {
			arg0 = args[0].(EventHandler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_RegisterGlobalHandler_Call) Return() *MockEventDispatcher_RegisterGlobalHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventDispatcher_RegisterGlobalHandler_Call) RunAndReturn(run func(handler EventHandler)) *MockEventDispatcher_RegisterGlobalHandler_Call {
	_c.Run(run)
	return _c
}

// RegisterHandler provides a mock function for the type MockEventDispatcher
func (_mock *MockEventDispatcher) RegisterHandler(eventType string, handler EventHandler) {
	_mock.Called(eventType, handler)
	return
}

// MockEventDispatcher_RegisterHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHandler'
type MockEventDispatcher_RegisterHandler_Call struct {
	*mock.Call
}

// RegisterHandler is a helper method to define mock.On call
//   - eventType string
//   - handler EventHandler
func (_e *MockEventDispatcher_Expecter) RegisterHandler(eventType interface{}, handler interface{}) *MockEventDispatcher_RegisterHandler_Call {
	return &MockEventDispatcher_RegisterHandler_Call{Call: _e.mock.On("RegisterHandler", eventType, handler)}
}

func (_c *MockEventDispatcher_RegisterHandler_Call) Run(run func(eventType string, handler EventHandler)) *MockEventDispatcher_RegisterHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 EventHandler
		if args[1] != nil {
			arg1 = args[1].(EventHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventDispatcher_RegisterHandler_Call) Return() *MockEventDispatcher_RegisterHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventDispatcher_RegisterHandler_Call) RunAndReturn(run func(eventType string, handler EventHandler)) *MockEventDispatcher_RegisterHandler_Call {
	_c.Run(run)
	return _c
}

// NewMockComplexityEvaluator creates a new instance of MockComplexityEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockComplexityEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockComplexityEvaluator {
	mock := &MockComplexityEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockComplexityEvaluator is an autogenerated mock type for the ComplexityEvaluator type
type MockComplexityEvaluator struct {
	mock.Mock
}

type MockComplexityEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockComplexityEvaluator) EXPECT() *MockComplexityEvaluator_Expecter {
	return &MockComplexityEvaluator_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockComplexityEvaluator
func (_mock *MockComplexityEvaluator) Evaluate(design *entity.Design, codebaseInfo *CodebaseInfo, weights *ComplexityWeights) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error) {
	ret := _mock.Called(design, codebaseInfo, weights)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 valueobject.ComplexityScore
	var r1 valueobject.ComplexityDimensions
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Design, *CodebaseInfo, *ComplexityWeights) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error)); ok {
		return returnFunc(design, codebaseInfo, weights)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.Design, *CodebaseInfo, *ComplexityWeights) valueobject.ComplexityScore); ok {
		r0 = returnFunc(design, codebaseInfo, weights)
	} else {
		r0 = ret.Get(0).(valueobject.ComplexityScore)
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.Design, *CodebaseInfo, *ComplexityWeights) valueobject.ComplexityDimensions); ok {
		r1 = returnFunc(design, codebaseInfo, weights)
	} else {
		r1 = ret.Get(1).(valueobject.ComplexityDimensions)
	}
	if returnFunc, ok := ret.Get(2).(func(*entity.Design, *CodebaseInfo, *ComplexityWeights) error); ok {
		r2 = returnFunc(design, codebaseInfo, weights)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockComplexityEvaluator_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockComplexityEvaluator_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - design *entity.Design
//   - codebaseInfo *CodebaseInfo
//   - weights *ComplexityWeights
func (_e *MockComplexityEvaluator_Expecter) Evaluate(design interface{}, codebaseInfo interface{}, weights interface{}) *MockComplexityEvaluator_Evaluate_Call {
	return &MockComplexityEvaluator_Evaluate_Call{Call: _e.mock.On("Evaluate", design, codebaseInfo, weights)}
}

func (_c *MockComplexityEvaluator_Evaluate_Call) Run(run func(design *entity.Design, codebaseInfo *CodebaseInfo, weights *ComplexityWeights)) *MockComplexityEvaluator_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Design
		if args[0] != nil {
			arg0 = args[0].(*entity.Design)
		}
		var arg1 *CodebaseInfo
		if args[1] != nil {
			arg1 = args[1].(*CodebaseInfo)
		}
		var arg2 *ComplexityWeights
		if args[2] != nil {
			arg2 = args[2].(*ComplexityWeights)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockComplexityEvaluator_Evaluate_Call) Return(complexityScore valueobject.ComplexityScore, complexityDimensions valueobject.ComplexityDimensions, err error) *MockComplexityEvaluator_Evaluate_Call {
	_c.Call.Return(complexityScore, complexityDimensions, err)
	return _c
}

func (_c *MockComplexityEvaluator_Evaluate_Call) RunAndReturn(run func(design *entity.Design, codebaseInfo *CodebaseInfo, weights *ComplexityWeights) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error)) *MockComplexityEvaluator_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateWithDefaultWeights provides a mock function for the type MockComplexityEvaluator
func (_mock *MockComplexityEvaluator) EvaluateWithDefaultWeights(design *entity.Design, codebaseInfo *CodebaseInfo) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error) {
	ret := _mock.Called(design, codebaseInfo)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateWithDefaultWeights")
	}

	var r0 valueobject.ComplexityScore
	var r1 valueobject.ComplexityDimensions
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*entity.Design, *CodebaseInfo) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error)); ok {
		return returnFunc(design, codebaseInfo)
	}
	if returnFunc, ok := ret.Get(0).(func(*entity.Design, *CodebaseInfo) valueobject.ComplexityScore); ok {
		r0 = returnFunc(design, codebaseInfo)
	} else {
		r0 = ret.Get(0).(valueobject.ComplexityScore)
	}
	if returnFunc, ok := ret.Get(1).(func(*entity.Design, *CodebaseInfo) valueobject.ComplexityDimensions); ok {
		r1 = returnFunc(design, codebaseInfo)
	} else {
		r1 = ret.Get(1).(valueobject.ComplexityDimensions)
	}
	if returnFunc, ok := ret.Get(2).(func(*entity.Design, *CodebaseInfo) error); ok {
		r2 = returnFunc(design, codebaseInfo)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockComplexityEvaluator_EvaluateWithDefaultWeights_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateWithDefaultWeights'
type MockComplexityEvaluator_EvaluateWithDefaultWeights_Call struct {
	*mock.Call
}

// EvaluateWithDefaultWeights is a helper method to define mock.On call
//   - design *entity.Design
//   - codebaseInfo *CodebaseInfo
func (_e *MockComplexityEvaluator_Expecter) EvaluateWithDefaultWeights(design interface{}, codebaseInfo interface{}) *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call {
	return &MockComplexityEvaluator_EvaluateWithDefaultWeights_Call{Call: _e.mock.On("EvaluateWithDefaultWeights", design, codebaseInfo)}
}

func (_c *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call) Run(run func(design *entity.Design, codebaseInfo *CodebaseInfo)) *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Design
		if args[0] != nil {
			arg0 = args[0].(*entity.Design)
		}
		var arg1 *CodebaseInfo
		if args[1] != nil {
			arg1 = args[1].(*CodebaseInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call) Return(complexityScore valueobject.ComplexityScore, complexityDimensions valueobject.ComplexityDimensions, err error) *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call {
	_c.Call.Return(complexityScore, complexityDimensions, err)
	return _c
}

func (_c *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call) RunAndReturn(run func(design *entity.Design, codebaseInfo *CodebaseInfo) (valueobject.ComplexityScore, valueobject.ComplexityDimensions, error)) *MockComplexityEvaluator_EvaluateWithDefaultWeights_Call {
	_c.Call.Return(run)
	return _c
}

// GetThreshold provides a mock function for the type MockComplexityEvaluator
func (_mock *MockComplexityEvaluator) GetThreshold() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetThreshold")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockComplexityEvaluator_GetThreshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetThreshold'
type MockComplexityEvaluator_GetThreshold_Call struct {
	*mock.Call
}

// GetThreshold is a helper method to define mock.On call
func (_e *MockComplexityEvaluator_Expecter) GetThreshold() *MockComplexityEvaluator_GetThreshold_Call {
	return &MockComplexityEvaluator_GetThreshold_Call{Call: _e.mock.On("GetThreshold")}
}

func (_c *MockComplexityEvaluator_GetThreshold_Call) Run(run func()) *MockComplexityEvaluator_GetThreshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockComplexityEvaluator_GetThreshold_Call) Return(n int) *MockComplexityEvaluator_GetThreshold_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockComplexityEvaluator_GetThreshold_Call) RunAndReturn(run func() int) *MockComplexityEvaluator_GetThreshold_Call {
	_c.Call.Return(run)
	return _c
}

// SetThreshold provides a mock function for the type MockComplexityEvaluator
func (_mock *MockComplexityEvaluator) SetThreshold(threshold int) error {
	ret := _mock.Called(threshold)

	if len(ret) == 0 {
		panic("no return value specified for SetThreshold")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(threshold)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockComplexityEvaluator_SetThreshold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetThreshold'
type MockComplexityEvaluator_SetThreshold_Call struct {
	*mock.Call
}

// SetThreshold is a helper method to define mock.On call
//   - threshold int
func (_e *MockComplexityEvaluator_Expecter) SetThreshold(threshold interface{}) *MockComplexityEvaluator_SetThreshold_Call {
	return &MockComplexityEvaluator_SetThreshold_Call{Call: _e.mock.On("SetThreshold", threshold)}
}

func (_c *MockComplexityEvaluator_SetThreshold_Call) Run(run func(threshold int)) *MockComplexityEvaluator_SetThreshold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockComplexityEvaluator_SetThreshold_Call) Return(err error) *MockComplexityEvaluator_SetThreshold_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockComplexityEvaluator_SetThreshold_Call) RunAndReturn(run func(threshold int) error) *MockComplexityEvaluator_SetThreshold_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStageTransitionService creates a new instance of MockStageTransitionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStageTransitionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStageTransitionService {
	mock := &MockStageTransitionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStageTransitionService is an autogenerated mock type for the StageTransitionService type
type MockStageTransitionService struct {
	mock.Mock
}

type MockStageTransitionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStageTransitionService) EXPECT() *MockStageTransitionService_Expecter {
	return &MockStageTransitionService_Expecter{mock: &_m.Mock}
}

// CanRollback provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) CanRollback(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) bool {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for CanRollback")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) bool); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStageTransitionService_CanRollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanRollback'
type MockStageTransitionService_CanRollback_Call struct {
	*mock.Call
}

// CanRollback is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) CanRollback(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_CanRollback_Call {
	return &MockStageTransitionService_CanRollback_Call{Call: _e.mock.On("CanRollback", session, target, ctx)}
}

func (_c *MockStageTransitionService_CanRollback_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_CanRollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_CanRollback_Call) Return(b bool) *MockStageTransitionService_CanRollback_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStageTransitionService_CanRollback_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) bool) *MockStageTransitionService_CanRollback_Call {
	_c.Call.Return(run)
	return _c
}

// CanTransition provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) CanTransition(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) bool {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for CanTransition")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) bool); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStageTransitionService_CanTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanTransition'
type MockStageTransitionService_CanTransition_Call struct {
	*mock.Call
}

// CanTransition is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) CanTransition(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_CanTransition_Call {
	return &MockStageTransitionService_CanTransition_Call{Call: _e.mock.On("CanTransition", session, target, ctx)}
}

func (_c *MockStageTransitionService_CanTransition_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_CanTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_CanTransition_Call) Return(b bool) *MockStageTransitionService_CanTransition_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStageTransitionService_CanTransition_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) bool) *MockStageTransitionService_CanTransition_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateRollback provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) EvaluateRollback(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) RollbackResult {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateRollback")
	}

	var r0 RollbackResult
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) RollbackResult); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Get(0).(RollbackResult)
	}
	return r0
}

// MockStageTransitionService_EvaluateRollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateRollback'
type MockStageTransitionService_EvaluateRollback_Call struct {
	*mock.Call
}

// EvaluateRollback is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) EvaluateRollback(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_EvaluateRollback_Call {
	return &MockStageTransitionService_EvaluateRollback_Call{Call: _e.mock.On("EvaluateRollback", session, target, ctx)}
}

func (_c *MockStageTransitionService_EvaluateRollback_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_EvaluateRollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_EvaluateRollback_Call) Return(rollbackResult RollbackResult) *MockStageTransitionService_EvaluateRollback_Call {
	_c.Call.Return(rollbackResult)
	return _c
}

func (_c *MockStageTransitionService_EvaluateRollback_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) RollbackResult) *MockStageTransitionService_EvaluateRollback_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateTransition provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) EvaluateTransition(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) TransitionResult {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateTransition")
	}

	var r0 TransitionResult
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) TransitionResult); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Get(0).(TransitionResult)
	}
	return r0
}

// MockStageTransitionService_EvaluateTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateTransition'
type MockStageTransitionService_EvaluateTransition_Call struct {
	*mock.Call
}

// EvaluateTransition is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) EvaluateTransition(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_EvaluateTransition_Call {
	return &MockStageTransitionService_EvaluateTransition_Call{Call: _e.mock.On("EvaluateTransition", session, target, ctx)}
}

func (_c *MockStageTransitionService_EvaluateTransition_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_EvaluateTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_EvaluateTransition_Call) Return(transitionResult TransitionResult) *MockStageTransitionService_EvaluateTransition_Call {
	_c.Call.Return(transitionResult)
	return _c
}

func (_c *MockStageTransitionService_EvaluateTransition_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) TransitionResult) *MockStageTransitionService_EvaluateTransition_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllowedRollbackTargets provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) GetAllowedRollbackTargets(session *aggregate.WorkSession, ctx TransitionContext) []valueobject.Stage {
	ret := _mock.Called(session, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllowedRollbackTargets")
	}

	var r0 []valueobject.Stage
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, TransitionContext) []valueobject.Stage); ok {
		r0 = returnFunc(session, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]valueobject.Stage)
		}
	}
	return r0
}

// MockStageTransitionService_GetAllowedRollbackTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllowedRollbackTargets'
type MockStageTransitionService_GetAllowedRollbackTargets_Call struct {
	*mock.Call
}

// GetAllowedRollbackTargets is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) GetAllowedRollbackTargets(session interface{}, ctx interface{}) *MockStageTransitionService_GetAllowedRollbackTargets_Call {
	return &MockStageTransitionService_GetAllowedRollbackTargets_Call{Call: _e.mock.On("GetAllowedRollbackTargets", session, ctx)}
}

func (_c *MockStageTransitionService_GetAllowedRollbackTargets_Call) Run(run func(session *aggregate.WorkSession, ctx TransitionContext)) *MockStageTransitionService_GetAllowedRollbackTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 TransitionContext
		if args[1] != nil {
			arg1 = args[1].(TransitionContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_GetAllowedRollbackTargets_Call) Return(stages []valueobject.Stage) *MockStageTransitionService_GetAllowedRollbackTargets_Call {
	_c.Call.Return(stages)
	return _c
}

func (_c *MockStageTransitionService_GetAllowedRollbackTargets_Call) RunAndReturn(run func(session *aggregate.WorkSession, ctx TransitionContext) []valueobject.Stage) *MockStageTransitionService_GetAllowedRollbackTargets_Call {
	_c.Call.Return(run)
	return _c
}

// GetRollbackError provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) GetRollbackError(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRollbackError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) error); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageTransitionService_GetRollbackError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRollbackError'
type MockStageTransitionService_GetRollbackError_Call struct {
	*mock.Call
}

// GetRollbackError is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) GetRollbackError(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_GetRollbackError_Call {
	return &MockStageTransitionService_GetRollbackError_Call{Call: _e.mock.On("GetRollbackError", session, target, ctx)}
}

func (_c *MockStageTransitionService_GetRollbackError_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_GetRollbackError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_GetRollbackError_Call) Return(err error) *MockStageTransitionService_GetRollbackError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageTransitionService_GetRollbackError_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error) *MockStageTransitionService_GetRollbackError_Call {
	_c.Call.Return(run)
	return _c
}

// GetRollbackRule provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) GetRollbackRule(currentStage valueobject.Stage, targetStage valueobject.Stage) string {
	ret := _mock.Called(currentStage, targetStage)

	if len(ret) == 0 {
		panic("no return value specified for GetRollbackRule")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(valueobject.Stage, valueobject.Stage) string); ok {
		r0 = returnFunc(currentStage, targetStage)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStageTransitionService_GetRollbackRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRollbackRule'
type MockStageTransitionService_GetRollbackRule_Call struct {
	*mock.Call
}

// GetRollbackRule is a helper method to define mock.On call
//   - currentStage valueobject.Stage
//   - targetStage valueobject.Stage
func (_e *MockStageTransitionService_Expecter) GetRollbackRule(currentStage interface{}, targetStage interface{}) *MockStageTransitionService_GetRollbackRule_Call {
	return &MockStageTransitionService_GetRollbackRule_Call{Call: _e.mock.On("GetRollbackRule", currentStage, targetStage)}
}

func (_c *MockStageTransitionService_GetRollbackRule_Call) Run(run func(currentStage valueobject.Stage, targetStage valueobject.Stage)) *MockStageTransitionService_GetRollbackRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 valueobject.Stage
		if args[0] != nil {
			arg0 = args[0].(valueobject.Stage)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_GetRollbackRule_Call) Return(s string) *MockStageTransitionService_GetRollbackRule_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStageTransitionService_GetRollbackRule_Call) RunAndReturn(run func(currentStage valueobject.Stage, targetStage valueobject.Stage) string) *MockStageTransitionService_GetRollbackRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitionError provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) GetTransitionError(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitionError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) error); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageTransitionService_GetTransitionError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitionError'
type MockStageTransitionService_GetTransitionError_Call struct {
	*mock.Call
}

// GetTransitionError is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) GetTransitionError(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_GetTransitionError_Call {
	return &MockStageTransitionService_GetTransitionError_Call{Call: _e.mock.On("GetTransitionError", session, target, ctx)}
}

func (_c *MockStageTransitionService_GetTransitionError_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_GetTransitionError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_GetTransitionError_Call) Return(err error) *MockStageTransitionService_GetTransitionError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageTransitionService_GetTransitionError_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error) *MockStageTransitionService_GetTransitionError_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRollbackConditions provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) ValidateRollbackConditions(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRollbackConditions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) error); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageTransitionService_ValidateRollbackConditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRollbackConditions'
type MockStageTransitionService_ValidateRollbackConditions_Call struct {
	*mock.Call
}

// ValidateRollbackConditions is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) ValidateRollbackConditions(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_ValidateRollbackConditions_Call {
	return &MockStageTransitionService_ValidateRollbackConditions_Call{Call: _e.mock.On("ValidateRollbackConditions", session, target, ctx)}
}

func (_c *MockStageTransitionService_ValidateRollbackConditions_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_ValidateRollbackConditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_ValidateRollbackConditions_Call) Return(err error) *MockStageTransitionService_ValidateRollbackConditions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageTransitionService_ValidateRollbackConditions_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error) *MockStageTransitionService_ValidateRollbackConditions_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRollbackPreconditions provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) ValidateRollbackPreconditions(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRollbackPreconditions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) error); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageTransitionService_ValidateRollbackPreconditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRollbackPreconditions'
type MockStageTransitionService_ValidateRollbackPreconditions_Call struct {
	*mock.Call
}

// ValidateRollbackPreconditions is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) ValidateRollbackPreconditions(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_ValidateRollbackPreconditions_Call {
	return &MockStageTransitionService_ValidateRollbackPreconditions_Call{Call: _e.mock.On("ValidateRollbackPreconditions", session, target, ctx)}
}

func (_c *MockStageTransitionService_ValidateRollbackPreconditions_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_ValidateRollbackPreconditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_ValidateRollbackPreconditions_Call) Return(err error) *MockStageTransitionService_ValidateRollbackPreconditions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageTransitionService_ValidateRollbackPreconditions_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error) *MockStageTransitionService_ValidateRollbackPreconditions_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTransitionPreconditions provides a mock function for the type MockStageTransitionService
func (_mock *MockStageTransitionService) ValidateTransitionPreconditions(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error {
	ret := _mock.Called(session, target, ctx)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTransitionPreconditions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, TransitionContext) error); ok {
		r0 = returnFunc(session, target, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStageTransitionService_ValidateTransitionPreconditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTransitionPreconditions'
type MockStageTransitionService_ValidateTransitionPreconditions_Call struct {
	*mock.Call
}

// ValidateTransitionPreconditions is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - ctx TransitionContext
func (_e *MockStageTransitionService_Expecter) ValidateTransitionPreconditions(session interface{}, target interface{}, ctx interface{}) *MockStageTransitionService_ValidateTransitionPreconditions_Call {
	return &MockStageTransitionService_ValidateTransitionPreconditions_Call{Call: _e.mock.On("ValidateTransitionPreconditions", session, target, ctx)}
}

func (_c *MockStageTransitionService_ValidateTransitionPreconditions_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext)) *MockStageTransitionService_ValidateTransitionPreconditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 TransitionContext
		if args[2] != nil {
			arg2 = args[2].(TransitionContext)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStageTransitionService_ValidateTransitionPreconditions_Call) Return(err error) *MockStageTransitionService_ValidateTransitionPreconditions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStageTransitionService_ValidateTransitionPreconditions_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, ctx TransitionContext) error) *MockStageTransitionService_ValidateTransitionPreconditions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskScheduler creates a new instance of MockTaskScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskScheduler {
	mock := &MockTaskScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskScheduler is an autogenerated mock type for the TaskScheduler type
type MockTaskScheduler struct {
	mock.Mock
}

type MockTaskScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskScheduler) EXPECT() *MockTaskScheduler_Expecter {
	return &MockTaskScheduler_Expecter{mock: &_m.Mock}
}

// CanRetryTask provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) CanRetryTask(task *entity.Task, completedIDs []uuid.UUID, maxRetryLimit int) bool {
	ret := _mock.Called(task, completedIDs, maxRetryLimit)

	if len(ret) == 0 {
		panic("no return value specified for CanRetryTask")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*entity.Task, []uuid.UUID, int) bool); ok {
		r0 = returnFunc(task, completedIDs, maxRetryLimit)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTaskScheduler_CanRetryTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanRetryTask'
type MockTaskScheduler_CanRetryTask_Call struct {
	*mock.Call
}

// CanRetryTask is a helper method to define mock.On call
//   - task *entity.Task
//   - completedIDs []uuid.UUID
//   - maxRetryLimit int
func (_e *MockTaskScheduler_Expecter) CanRetryTask(task interface{}, completedIDs interface{}, maxRetryLimit interface{}) *MockTaskScheduler_CanRetryTask_Call {
	return &MockTaskScheduler_CanRetryTask_Call{Call: _e.mock.On("CanRetryTask", task, completedIDs, maxRetryLimit)}
}

func (_c *MockTaskScheduler_CanRetryTask_Call) Run(run func(task *entity.Task, completedIDs []uuid.UUID, maxRetryLimit int)) *MockTaskScheduler_CanRetryTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entity.Task
		if args[0] != nil {
			arg0 = args[0].(*entity.Task)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_CanRetryTask_Call) Return(b bool) *MockTaskScheduler_CanRetryTask_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTaskScheduler_CanRetryTask_Call) RunAndReturn(run func(task *entity.Task, completedIDs []uuid.UUID, maxRetryLimit int) bool) *MockTaskScheduler_CanRetryTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedTasks provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetBlockedTasks(tasks []*entity.Task, completedIDs []uuid.UUID) []*entity.Task {
	ret := _mock.Called(tasks, completedIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedTasks")
	}

	var r0 []*entity.Task
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task, []uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(tasks, completedIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	return r0
}

// MockTaskScheduler_GetBlockedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedTasks'
type MockTaskScheduler_GetBlockedTasks_Call struct {
	*mock.Call
}

// GetBlockedTasks is a helper method to define mock.On call
//   - tasks []*entity.Task
//   - completedIDs []uuid.UUID
func (_e *MockTaskScheduler_Expecter) GetBlockedTasks(tasks interface{}, completedIDs interface{}) *MockTaskScheduler_GetBlockedTasks_Call {
	return &MockTaskScheduler_GetBlockedTasks_Call{Call: _e.mock.On("GetBlockedTasks", tasks, completedIDs)}
}

func (_c *MockTaskScheduler_GetBlockedTasks_Call) Run(run func(tasks []*entity.Task, completedIDs []uuid.UUID)) *MockTaskScheduler_GetBlockedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetBlockedTasks_Call) Return(tasks1 []*entity.Task) *MockTaskScheduler_GetBlockedTasks_Call {
	_c.Call.Return(tasks1)
	return _c
}

func (_c *MockTaskScheduler_GetBlockedTasks_Call) RunAndReturn(run func(tasks []*entity.Task, completedIDs []uuid.UUID) []*entity.Task) *MockTaskScheduler_GetBlockedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependencyGraph provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetDependencyGraph(tasks []*entity.Task) map[uuid.UUID][]uuid.UUID {
	ret := _mock.Called(tasks)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyGraph")
	}

	var r0 map[uuid.UUID][]uuid.UUID
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) map[uuid.UUID][]uuid.UUID); ok {
		r0 = returnFunc(tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]uuid.UUID)
		}
	}
	return r0
}

// MockTaskScheduler_GetDependencyGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependencyGraph'
type MockTaskScheduler_GetDependencyGraph_Call struct {
	*mock.Call
}

// GetDependencyGraph is a helper method to define mock.On call
//   - tasks []*entity.Task
func (_e *MockTaskScheduler_Expecter) GetDependencyGraph(tasks interface{}) *MockTaskScheduler_GetDependencyGraph_Call {
	return &MockTaskScheduler_GetDependencyGraph_Call{Call: _e.mock.On("GetDependencyGraph", tasks)}
}

func (_c *MockTaskScheduler_GetDependencyGraph_Call) Run(run func(tasks []*entity.Task)) *MockTaskScheduler_GetDependencyGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetDependencyGraph_Call) Return(uUIDToUUIDs map[uuid.UUID][]uuid.UUID) *MockTaskScheduler_GetDependencyGraph_Call {
	_c.Call.Return(uUIDToUUIDs)
	return _c
}

func (_c *MockTaskScheduler_GetDependencyGraph_Call) RunAndReturn(run func(tasks []*entity.Task) map[uuid.UUID][]uuid.UUID) *MockTaskScheduler_GetDependencyGraph_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionOrder provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetExecutionOrder(tasks []*entity.Task) ([]*entity.Task, error) {
	ret := _mock.Called(tasks)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionOrder")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) ([]*entity.Task, error)); ok {
		return returnFunc(tasks)
	}
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) []*entity.Task); ok {
		r0 = returnFunc(tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*entity.Task) error); ok {
		r1 = returnFunc(tasks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskScheduler_GetExecutionOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionOrder'
type MockTaskScheduler_GetExecutionOrder_Call struct {
	*mock.Call
}

// GetExecutionOrder is a helper method to define mock.On call
//   - tasks []*entity.Task
func (_e *MockTaskScheduler_Expecter) GetExecutionOrder(tasks interface{}) *MockTaskScheduler_GetExecutionOrder_Call {
	return &MockTaskScheduler_GetExecutionOrder_Call{Call: _e.mock.On("GetExecutionOrder", tasks)}
}

func (_c *MockTaskScheduler_GetExecutionOrder_Call) Run(run func(tasks []*entity.Task)) *MockTaskScheduler_GetExecutionOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetExecutionOrder_Call) Return(tasks1 []*entity.Task, err error) *MockTaskScheduler_GetExecutionOrder_Call {
	_c.Call.Return(tasks1, err)
	return _c
}

func (_c *MockTaskScheduler_GetExecutionOrder_Call) RunAndReturn(run func(tasks []*entity.Task) ([]*entity.Task, error)) *MockTaskScheduler_GetExecutionOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionPlan provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetExecutionPlan(tasks []*entity.Task) ([][]*entity.Task, error) {
	ret := _mock.Called(tasks)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionPlan")
	}

	var r0 [][]*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) ([][]*entity.Task, error)); ok {
		return returnFunc(tasks)
	}
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) [][]*entity.Task); ok {
		r0 = returnFunc(tasks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*entity.Task) error); ok {
		r1 = returnFunc(tasks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskScheduler_GetExecutionPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionPlan'
type MockTaskScheduler_GetExecutionPlan_Call struct {
	*mock.Call
}

// GetExecutionPlan is a helper method to define mock.On call
//   - tasks []*entity.Task
func (_e *MockTaskScheduler_Expecter) GetExecutionPlan(tasks interface{}) *MockTaskScheduler_GetExecutionPlan_Call {
	return &MockTaskScheduler_GetExecutionPlan_Call{Call: _e.mock.On("GetExecutionPlan", tasks)}
}

func (_c *MockTaskScheduler_GetExecutionPlan_Call) Run(run func(tasks []*entity.Task)) *MockTaskScheduler_GetExecutionPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetExecutionPlan_Call) Return(taskss [][]*entity.Task, err error) *MockTaskScheduler_GetExecutionPlan_Call {
	_c.Call.Return(taskss, err)
	return _c
}

func (_c *MockTaskScheduler_GetExecutionPlan_Call) RunAndReturn(run func(tasks []*entity.Task) ([][]*entity.Task, error)) *MockTaskScheduler_GetExecutionPlan_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextExecutable provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetNextExecutable(tasks []*entity.Task, completedIDs []uuid.UUID, maxRetryLimit int) *entity.Task {
	ret := _mock.Called(tasks, completedIDs, maxRetryLimit)

	if len(ret) == 0 {
		panic("no return value specified for GetNextExecutable")
	}

	var r0 *entity.Task
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task, []uuid.UUID, int) *entity.Task); ok {
		r0 = returnFunc(tasks, completedIDs, maxRetryLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	return r0
}

// MockTaskScheduler_GetNextExecutable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextExecutable'
type MockTaskScheduler_GetNextExecutable_Call struct {
	*mock.Call
}

// GetNextExecutable is a helper method to define mock.On call
//   - tasks []*entity.Task
//   - completedIDs []uuid.UUID
//   - maxRetryLimit int
func (_e *MockTaskScheduler_Expecter) GetNextExecutable(tasks interface{}, completedIDs interface{}, maxRetryLimit interface{}) *MockTaskScheduler_GetNextExecutable_Call {
	return &MockTaskScheduler_GetNextExecutable_Call{Call: _e.mock.On("GetNextExecutable", tasks, completedIDs, maxRetryLimit)}
}

func (_c *MockTaskScheduler_GetNextExecutable_Call) Run(run func(tasks []*entity.Task, completedIDs []uuid.UUID, maxRetryLimit int)) *MockTaskScheduler_GetNextExecutable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetNextExecutable_Call) Return(task *entity.Task) *MockTaskScheduler_GetNextExecutable_Call {
	_c.Call.Return(task)
	return _c
}

func (_c *MockTaskScheduler_GetNextExecutable_Call) RunAndReturn(run func(tasks []*entity.Task, completedIDs []uuid.UUID, maxRetryLimit int) *entity.Task) *MockTaskScheduler_GetNextExecutable_Call {
	_c.Call.Return(run)
	return _c
}

// GetParallelTasks provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) GetParallelTasks(tasks []*entity.Task, completedIDs []uuid.UUID) []*entity.Task {
	ret := _mock.Called(tasks, completedIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetParallelTasks")
	}

	var r0 []*entity.Task
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task, []uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(tasks, completedIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	return r0
}

// MockTaskScheduler_GetParallelTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParallelTasks'
type MockTaskScheduler_GetParallelTasks_Call struct {
	*mock.Call
}

// GetParallelTasks is a helper method to define mock.On call
//   - tasks []*entity.Task
//   - completedIDs []uuid.UUID
func (_e *MockTaskScheduler_Expecter) GetParallelTasks(tasks interface{}, completedIDs interface{}) *MockTaskScheduler_GetParallelTasks_Call {
	return &MockTaskScheduler_GetParallelTasks_Call{Call: _e.mock.On("GetParallelTasks", tasks, completedIDs)}
}

func (_c *MockTaskScheduler_GetParallelTasks_Call) Run(run func(tasks []*entity.Task, completedIDs []uuid.UUID)) *MockTaskScheduler_GetParallelTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_GetParallelTasks_Call) Return(tasks1 []*entity.Task) *MockTaskScheduler_GetParallelTasks_Call {
	_c.Call.Return(tasks1)
	return _c
}

func (_c *MockTaskScheduler_GetParallelTasks_Call) RunAndReturn(run func(tasks []*entity.Task, completedIDs []uuid.UUID) []*entity.Task) *MockTaskScheduler_GetParallelTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDependencies provides a mock function for the type MockTaskScheduler
func (_mock *MockTaskScheduler) ValidateDependencies(tasks []*entity.Task) error {
	ret := _mock.Called(tasks)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDependencies")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*entity.Task) error); ok {
		r0 = returnFunc(tasks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskScheduler_ValidateDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDependencies'
type MockTaskScheduler_ValidateDependencies_Call struct {
	*mock.Call
}

// ValidateDependencies is a helper method to define mock.On call
//   - tasks []*entity.Task
func (_e *MockTaskScheduler_Expecter) ValidateDependencies(tasks interface{}) *MockTaskScheduler_ValidateDependencies_Call {
	return &MockTaskScheduler_ValidateDependencies_Call{Call: _e.mock.On("ValidateDependencies", tasks)}
}

func (_c *MockTaskScheduler_ValidateDependencies_Call) Run(run func(tasks []*entity.Task)) *MockTaskScheduler_ValidateDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*entity.Task
		if args[0] != nil {
			arg0 = args[0].([]*entity.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskScheduler_ValidateDependencies_Call) Return(err error) *MockTaskScheduler_ValidateDependencies_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskScheduler_ValidateDependencies_Call) RunAndReturn(run func(tasks []*entity.Task) error) *MockTaskScheduler_ValidateDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionControlService creates a new instance of MockSessionControlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionControlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionControlService {
	mock := &MockSessionControlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionControlService is an autogenerated mock type for the SessionControlService type
type MockSessionControlService struct {
	mock.Mock
}

type MockSessionControlService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionControlService) EXPECT() *MockSessionControlService_Expecter {
	return &MockSessionControlService_Expecter{mock: &_m.Mock}
}

// AutoResumeSession provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) AutoResumeSession(session *aggregate.WorkSession) (bool, error) {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for AutoResumeSession")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession) (bool, error)); ok {
		return returnFunc(session)
	}
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession) bool); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*aggregate.WorkSession) error); ok {
		r1 = returnFunc(session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionControlService_AutoResumeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoResumeSession'
type MockSessionControlService_AutoResumeSession_Call struct {
	*mock.Call
}

// AutoResumeSession is a helper method to define mock.On call
//   - session *aggregate.WorkSession
func (_e *MockSessionControlService_Expecter) AutoResumeSession(session interface{}) *MockSessionControlService_AutoResumeSession_Call {
	return &MockSessionControlService_AutoResumeSession_Call{Call: _e.mock.On("AutoResumeSession", session)}
}

func (_c *MockSessionControlService_AutoResumeSession_Call) Run(run func(session *aggregate.WorkSession)) *MockSessionControlService_AutoResumeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionControlService_AutoResumeSession_Call) Return(b bool, err error) *MockSessionControlService_AutoResumeSession_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSessionControlService_AutoResumeSession_Call) RunAndReturn(run func(session *aggregate.WorkSession) (bool, error)) *MockSessionControlService_AutoResumeSession_Call {
	_c.Call.Return(run)
	return _c
}

// CanResumeWithAction provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) CanResumeWithAction(session *aggregate.WorkSession, action string) bool {
	ret := _mock.Called(session, action)

	if len(ret) == 0 {
		panic("no return value specified for CanResumeWithAction")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, string) bool); ok {
		r0 = returnFunc(session, action)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSessionControlService_CanResumeWithAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanResumeWithAction'
type MockSessionControlService_CanResumeWithAction_Call struct {
	*mock.Call
}

// CanResumeWithAction is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - action string
func (_e *MockSessionControlService_Expecter) CanResumeWithAction(session interface{}, action interface{}) *MockSessionControlService_CanResumeWithAction_Call {
	return &MockSessionControlService_CanResumeWithAction_Call{Call: _e.mock.On("CanResumeWithAction", session, action)}
}

func (_c *MockSessionControlService_CanResumeWithAction_Call) Run(run func(session *aggregate.WorkSession, action string)) *MockSessionControlService_CanResumeWithAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionControlService_CanResumeWithAction_Call) Return(b bool) *MockSessionControlService_CanResumeWithAction_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSessionControlService_CanResumeWithAction_Call) RunAndReturn(run func(session *aggregate.WorkSession, action string) bool) *MockSessionControlService_CanResumeWithAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetValidResumeActions provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) GetValidResumeActions(session *aggregate.WorkSession) []string {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for GetValidResumeActions")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession) []string); ok {
		r0 = returnFunc(session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockSessionControlService_GetValidResumeActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValidResumeActions'
type MockSessionControlService_GetValidResumeActions_Call struct {
	*mock.Call
}

// GetValidResumeActions is a helper method to define mock.On call
//   - session *aggregate.WorkSession
func (_e *MockSessionControlService_Expecter) GetValidResumeActions(session interface{}) *MockSessionControlService_GetValidResumeActions_Call {
	return &MockSessionControlService_GetValidResumeActions_Call{Call: _e.mock.On("GetValidResumeActions", session)}
}

func (_c *MockSessionControlService_GetValidResumeActions_Call) Run(run func(session *aggregate.WorkSession)) *MockSessionControlService_GetValidResumeActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionControlService_GetValidResumeActions_Call) Return(strings []string) *MockSessionControlService_GetValidResumeActions_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockSessionControlService_GetValidResumeActions_Call) RunAndReturn(run func(session *aggregate.WorkSession) []string) *MockSessionControlService_GetValidResumeActions_Call {
	_c.Call.Return(run)
	return _c
}

// PauseSession provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) PauseSession(session *aggregate.WorkSession, ctx valueobject.PauseContext) error {
	ret := _mock.Called(session, ctx)

	if len(ret) == 0 {
		panic("no return value specified for PauseSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.PauseContext) error); ok {
		r0 = returnFunc(session, ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionControlService_PauseSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseSession'
type MockSessionControlService_PauseSession_Call struct {
	*mock.Call
}

// PauseSession is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - ctx valueobject.PauseContext
func (_e *MockSessionControlService_Expecter) PauseSession(session interface{}, ctx interface{}) *MockSessionControlService_PauseSession_Call {
	return &MockSessionControlService_PauseSession_Call{Call: _e.mock.On("PauseSession", session, ctx)}
}

func (_c *MockSessionControlService_PauseSession_Call) Run(run func(session *aggregate.WorkSession, ctx valueobject.PauseContext)) *MockSessionControlService_PauseSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.PauseContext
		if args[1] != nil {
			arg1 = args[1].(valueobject.PauseContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionControlService_PauseSession_Call) Return(err error) *MockSessionControlService_PauseSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionControlService_PauseSession_Call) RunAndReturn(run func(session *aggregate.WorkSession, ctx valueobject.PauseContext) error) *MockSessionControlService_PauseSession_Call {
	_c.Call.Return(run)
	return _c
}

// ResumeSession provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) ResumeSession(session *aggregate.WorkSession, action string) error {
	ret := _mock.Called(session, action)

	if len(ret) == 0 {
		panic("no return value specified for ResumeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, string) error); ok {
		r0 = returnFunc(session, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionControlService_ResumeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumeSession'
type MockSessionControlService_ResumeSession_Call struct {
	*mock.Call
}

// ResumeSession is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - action string
func (_e *MockSessionControlService_Expecter) ResumeSession(session interface{}, action interface{}) *MockSessionControlService_ResumeSession_Call {
	return &MockSessionControlService_ResumeSession_Call{Call: _e.mock.On("ResumeSession", session, action)}
}

func (_c *MockSessionControlService_ResumeSession_Call) Run(run func(session *aggregate.WorkSession, action string)) *MockSessionControlService_ResumeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionControlService_ResumeSession_Call) Return(err error) *MockSessionControlService_ResumeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionControlService_ResumeSession_Call) RunAndReturn(run func(session *aggregate.WorkSession, action string) error) *MockSessionControlService_ResumeSession_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackSession provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) RollbackSession(session *aggregate.WorkSession, target valueobject.Stage, reason string) error {
	ret := _mock.Called(session, target, reason)

	if len(ret) == 0 {
		panic("no return value specified for RollbackSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, valueobject.Stage, string) error); ok {
		r0 = returnFunc(session, target, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionControlService_RollbackSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackSession'
type MockSessionControlService_RollbackSession_Call struct {
	*mock.Call
}

// RollbackSession is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - target valueobject.Stage
//   - reason string
func (_e *MockSessionControlService_Expecter) RollbackSession(session interface{}, target interface{}, reason interface{}) *MockSessionControlService_RollbackSession_Call {
	return &MockSessionControlService_RollbackSession_Call{Call: _e.mock.On("RollbackSession", session, target, reason)}
}

func (_c *MockSessionControlService_RollbackSession_Call) Run(run func(session *aggregate.WorkSession, target valueobject.Stage, reason string)) *MockSessionControlService_RollbackSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 valueobject.Stage
		if args[1] != nil {
			arg1 = args[1].(valueobject.Stage)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionControlService_RollbackSession_Call) Return(err error) *MockSessionControlService_RollbackSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionControlService_RollbackSession_Call) RunAndReturn(run func(session *aggregate.WorkSession, target valueobject.Stage, reason string) error) *MockSessionControlService_RollbackSession_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateSession provides a mock function for the type MockSessionControlService
func (_mock *MockSessionControlService) TerminateSession(session *aggregate.WorkSession, reason string) error {
	ret := _mock.Called(session, reason)

	if len(ret) == 0 {
		panic("no return value specified for TerminateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*aggregate.WorkSession, string) error); ok {
		r0 = returnFunc(session, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionControlService_TerminateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateSession'
type MockSessionControlService_TerminateSession_Call struct {
	*mock.Call
}

// TerminateSession is a helper method to define mock.On call
//   - session *aggregate.WorkSession
//   - reason string
func (_e *MockSessionControlService_Expecter) TerminateSession(session interface{}, reason interface{}) *MockSessionControlService_TerminateSession_Call {
	return &MockSessionControlService_TerminateSession_Call{Call: _e.mock.On("TerminateSession", session, reason)}
}

func (_c *MockSessionControlService_TerminateSession_Call) Run(run func(session *aggregate.WorkSession, reason string)) *MockSessionControlService_TerminateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aggregate.WorkSession
		if args[0] != nil {
			arg0 = args[0].(*aggregate.WorkSession)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionControlService_TerminateSession_Call) Return(err error) *MockSessionControlService_TerminateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionControlService_TerminateSession_Call) RunAndReturn(run func(session *aggregate.WorkSession, reason string) error) *MockSessionControlService_TerminateSession_Call {
	_c.Call.Return(run)
	return _c
}
