/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type {
	ApiError,
	AuditLog,
	AuditSummary,
	GetApiV1AuditParams,
	GetApiV1AuditRepositoriesRepositoryParams,
	GetApiV1AuditSessionsSessionIdParams,
	PaginatedResponseAuditLog,
} from "../schemas";

/**
 * Retrieve audit logs with filtering by session, repository, actor, operation, result, and time range. Supports pagination.
 * @summary List audit logs
 */
export type getApiV1AuditResponse200 = {
	data: PaginatedResponseAuditLog;
	status: 200;
};

export type getApiV1AuditResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1AuditResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1AuditResponseSuccess = getApiV1AuditResponse200 & {
	headers: Headers;
};
export type getApiV1AuditResponseError = (
	| getApiV1AuditResponse400
	| getApiV1AuditResponse500
) & {
	headers: Headers;
};

export type getApiV1AuditResponse =
	| getApiV1AuditResponseSuccess
	| getApiV1AuditResponseError;

export const getGetApiV1AuditUrl = (params?: GetApiV1AuditParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/audit?${stringifiedParams}`
		: `/api/v1/audit`;
};

export const getApiV1Audit = async (
	params?: GetApiV1AuditParams,
	options?: RequestInit,
): Promise<getApiV1AuditResponse> => {
	const res = await fetch(getGetApiV1AuditUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1AuditResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1AuditResponse;
};

export const getGetApiV1AuditQueryKey = (params?: GetApiV1AuditParams) => {
	return [`/api/v1/audit`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1AuditQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Audit>>,
	TError = ApiError,
>(
	params?: GetApiV1AuditParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Audit>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1AuditQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Audit>>> = ({
		signal,
	}) => getApiV1Audit(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Audit>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuditQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Audit>>
>;
export type GetApiV1AuditQueryError = ApiError;

export function useGetApiV1Audit<
	TData = Awaited<ReturnType<typeof getApiV1Audit>>,
	TError = ApiError,
>(
	params: undefined | GetApiV1AuditParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Audit>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Audit>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Audit>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Audit<
	TData = Awaited<ReturnType<typeof getApiV1Audit>>,
	TError = ApiError,
>(
	params?: GetApiV1AuditParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Audit>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Audit>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Audit>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Audit<
	TData = Awaited<ReturnType<typeof getApiV1Audit>>,
	TError = ApiError,
>(
	params?: GetApiV1AuditParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Audit>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List audit logs
 */

export function useGetApiV1Audit<
	TData = Awaited<ReturnType<typeof getApiV1Audit>>,
	TError = ApiError,
>(
	params?: GetApiV1AuditParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Audit>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1AuditQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve all audit logs for a specific repository (owner/repo format). Supports pagination.
 * @summary List audit logs by repository
 */
export type getApiV1AuditRepositoriesRepositoryResponse200 = {
	data: PaginatedResponseAuditLog;
	status: 200;
};

export type getApiV1AuditRepositoriesRepositoryResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1AuditRepositoriesRepositoryResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1AuditRepositoriesRepositoryResponseSuccess =
	getApiV1AuditRepositoriesRepositoryResponse200 & {
		headers: Headers;
	};
export type getApiV1AuditRepositoriesRepositoryResponseError = (
	| getApiV1AuditRepositoriesRepositoryResponse400
	| getApiV1AuditRepositoriesRepositoryResponse500
) & {
	headers: Headers;
};

export type getApiV1AuditRepositoriesRepositoryResponse =
	| getApiV1AuditRepositoriesRepositoryResponseSuccess
	| getApiV1AuditRepositoriesRepositoryResponseError;

export const getGetApiV1AuditRepositoriesRepositoryUrl = (
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/audit/repositories/${repository}?${stringifiedParams}`
		: `/api/v1/audit/repositories/${repository}`;
};

export const getApiV1AuditRepositoriesRepository = async (
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
	options?: RequestInit,
): Promise<getApiV1AuditRepositoriesRepositoryResponse> => {
	const res = await fetch(
		getGetApiV1AuditRepositoriesRepositoryUrl(repository, params),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1AuditRepositoriesRepositoryResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1AuditRepositoriesRepositoryResponse;
};

export const getGetApiV1AuditRepositoriesRepositoryQueryKey = (
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
) => {
	return [
		`/api/v1/audit/repositories/${repository}`,
		...(params ? [params] : []),
	] as const;
};

export const getGetApiV1AuditRepositoriesRepositoryQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
	TError = ApiError,
>(
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1AuditRepositoriesRepositoryQueryKey(repository, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>
	> = ({ signal }) =>
		getApiV1AuditRepositoriesRepository(repository, params, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!repository,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuditRepositoriesRepositoryQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>
>;
export type GetApiV1AuditRepositoriesRepositoryQueryError = ApiError;

export function useGetApiV1AuditRepositoriesRepository<
	TData = Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
	TError = ApiError,
>(
	repository: string,
	params: undefined | GetApiV1AuditRepositoriesRepositoryParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditRepositoriesRepository<
	TData = Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
	TError = ApiError,
>(
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditRepositoriesRepository<
	TData = Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
	TError = ApiError,
>(
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List audit logs by repository
 */

export function useGetApiV1AuditRepositoriesRepository<
	TData = Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
	TError = ApiError,
>(
	repository: string,
	params?: GetApiV1AuditRepositoriesRepositoryParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditRepositoriesRepository>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1AuditRepositoriesRepositoryQueryOptions(
		repository,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve all audit logs associated with a specific work session. Supports pagination.
 * @summary List audit logs by session
 */
export type getApiV1AuditSessionsSessionIdResponse200 = {
	data: PaginatedResponseAuditLog;
	status: 200;
};

export type getApiV1AuditSessionsSessionIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1AuditSessionsSessionIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1AuditSessionsSessionIdResponseSuccess =
	getApiV1AuditSessionsSessionIdResponse200 & {
		headers: Headers;
	};
export type getApiV1AuditSessionsSessionIdResponseError = (
	| getApiV1AuditSessionsSessionIdResponse400
	| getApiV1AuditSessionsSessionIdResponse500
) & {
	headers: Headers;
};

export type getApiV1AuditSessionsSessionIdResponse =
	| getApiV1AuditSessionsSessionIdResponseSuccess
	| getApiV1AuditSessionsSessionIdResponseError;

export const getGetApiV1AuditSessionsSessionIdUrl = (
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/audit/sessions/${sessionId}?${stringifiedParams}`
		: `/api/v1/audit/sessions/${sessionId}`;
};

export const getApiV1AuditSessionsSessionId = async (
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
	options?: RequestInit,
): Promise<getApiV1AuditSessionsSessionIdResponse> => {
	const res = await fetch(
		getGetApiV1AuditSessionsSessionIdUrl(sessionId, params),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1AuditSessionsSessionIdResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1AuditSessionsSessionIdResponse;
};

export const getGetApiV1AuditSessionsSessionIdQueryKey = (
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
) => {
	return [
		`/api/v1/audit/sessions/${sessionId}`,
		...(params ? [params] : []),
	] as const;
};

export const getGetApiV1AuditSessionsSessionIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1AuditSessionsSessionIdQueryKey(sessionId, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>
	> = ({ signal }) =>
		getApiV1AuditSessionsSessionId(sessionId, params, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!sessionId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuditSessionsSessionIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>
>;
export type GetApiV1AuditSessionsSessionIdQueryError = ApiError;

export function useGetApiV1AuditSessionsSessionId<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
	TError = ApiError,
>(
	sessionId: string,
	params: undefined | GetApiV1AuditSessionsSessionIdParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditSessionsSessionId<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditSessionsSessionId<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List audit logs by session
 */

export function useGetApiV1AuditSessionsSessionId<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1AuditSessionsSessionIdParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1AuditSessionsSessionIdQueryOptions(
		sessionId,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve aggregated statistics of audit logs for a specific work session, including counts by operation type and result status.
 * @summary Get session audit summary
 */
export type getApiV1AuditSessionsSessionIdSummaryResponse200 = {
	data: AuditSummary;
	status: 200;
};

export type getApiV1AuditSessionsSessionIdSummaryResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1AuditSessionsSessionIdSummaryResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1AuditSessionsSessionIdSummaryResponseSuccess =
	getApiV1AuditSessionsSessionIdSummaryResponse200 & {
		headers: Headers;
	};
export type getApiV1AuditSessionsSessionIdSummaryResponseError = (
	| getApiV1AuditSessionsSessionIdSummaryResponse400
	| getApiV1AuditSessionsSessionIdSummaryResponse500
) & {
	headers: Headers;
};

export type getApiV1AuditSessionsSessionIdSummaryResponse =
	| getApiV1AuditSessionsSessionIdSummaryResponseSuccess
	| getApiV1AuditSessionsSessionIdSummaryResponseError;

export const getGetApiV1AuditSessionsSessionIdSummaryUrl = (
	sessionId: string,
) => {
	return `/api/v1/audit/sessions/${sessionId}/summary`;
};

export const getApiV1AuditSessionsSessionIdSummary = async (
	sessionId: string,
	options?: RequestInit,
): Promise<getApiV1AuditSessionsSessionIdSummaryResponse> => {
	const res = await fetch(
		getGetApiV1AuditSessionsSessionIdSummaryUrl(sessionId),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1AuditSessionsSessionIdSummaryResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1AuditSessionsSessionIdSummaryResponse;
};

export const getGetApiV1AuditSessionsSessionIdSummaryQueryKey = (
	sessionId: string,
) => {
	return [`/api/v1/audit/sessions/${sessionId}/summary`] as const;
};

export const getGetApiV1AuditSessionsSessionIdSummaryQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
	TError = ApiError,
>(
	sessionId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1AuditSessionsSessionIdSummaryQueryKey(sessionId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>
	> = ({ signal }) =>
		getApiV1AuditSessionsSessionIdSummary(sessionId, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!sessionId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuditSessionsSessionIdSummaryQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>
>;
export type GetApiV1AuditSessionsSessionIdSummaryQueryError = ApiError;

export function useGetApiV1AuditSessionsSessionIdSummary<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
	TError = ApiError,
>(
	sessionId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditSessionsSessionIdSummary<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
	TError = ApiError,
>(
	sessionId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditSessionsSessionIdSummary<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
	TError = ApiError,
>(
	sessionId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get session audit summary
 */

export function useGetApiV1AuditSessionsSessionIdSummary<
	TData = Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
	TError = ApiError,
>(
	sessionId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditSessionsSessionIdSummary>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1AuditSessionsSessionIdSummaryQueryOptions(
		sessionId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve a single audit log entry by its unique identifier.
 * @summary Get audit log
 */
export type getApiV1AuditIdResponse200 = {
	data: AuditLog;
	status: 200;
};

export type getApiV1AuditIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1AuditIdResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1AuditIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1AuditIdResponseSuccess = getApiV1AuditIdResponse200 & {
	headers: Headers;
};
export type getApiV1AuditIdResponseError = (
	| getApiV1AuditIdResponse400
	| getApiV1AuditIdResponse404
	| getApiV1AuditIdResponse500
) & {
	headers: Headers;
};

export type getApiV1AuditIdResponse =
	| getApiV1AuditIdResponseSuccess
	| getApiV1AuditIdResponseError;

export const getGetApiV1AuditIdUrl = (id: string) => {
	return `/api/v1/audit/${id}`;
};

export const getApiV1AuditId = async (
	id: string,
	options?: RequestInit,
): Promise<getApiV1AuditIdResponse> => {
	const res = await fetch(getGetApiV1AuditIdUrl(id), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1AuditIdResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1AuditIdResponse;
};

export const getGetApiV1AuditIdQueryKey = (id: string) => {
	return [`/api/v1/audit/${id}`] as const;
};

export const getGetApiV1AuditIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1AuditId>>,
	TError = ApiError,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetApiV1AuditIdQueryKey(id);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1AuditId>>> = ({
		signal,
	}) => getApiV1AuditId(id, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1AuditId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1AuditIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1AuditId>>
>;
export type GetApiV1AuditIdQueryError = ApiError;

export function useGetApiV1AuditId<
	TData = Awaited<ReturnType<typeof getApiV1AuditId>>,
	TError = ApiError,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditId<
	TData = Awaited<ReturnType<typeof getApiV1AuditId>>,
	TError = ApiError,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1AuditId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1AuditId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1AuditId<
	TData = Awaited<ReturnType<typeof getApiV1AuditId>>,
	TError = ApiError,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get audit log
 */

export function useGetApiV1AuditId<
	TData = Awaited<ReturnType<typeof getApiV1AuditId>>,
	TError = ApiError,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1AuditId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1AuditIdQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
