/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ApiError,
	Config,
	GetApiV1ConfigBody,
	PutApiV1ConfigBody,
} from "../schemas";

/**
 * Returns the current application configuration (sensitive fields excluded)
 * @summary Get configuration
 */
export type getApiV1ConfigResponse200 = {
	data: Config;
	status: 200;
};

export type getApiV1ConfigResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1ConfigResponseSuccess = getApiV1ConfigResponse200 & {
	headers: Headers;
};
export type getApiV1ConfigResponseError = getApiV1ConfigResponse500 & {
	headers: Headers;
};

export type getApiV1ConfigResponse =
	| getApiV1ConfigResponseSuccess
	| getApiV1ConfigResponseError;

export const getGetApiV1ConfigUrl = () => {
	return `/api/v1/config`;
};

export const getApiV1Config = async (
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options?: RequestInit,
): Promise<getApiV1ConfigResponse> => {
	const res = await fetch(getGetApiV1ConfigUrl(), {
		...options,
		method: "GET",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(getApiV1ConfigBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1ConfigResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1ConfigResponse;
};

export const getGetApiV1ConfigQueryKey = (
	getApiV1ConfigBody?: GetApiV1ConfigBody,
) => {
	return [`/api/v1/config`, getApiV1ConfigBody] as const;
};

export const getGetApiV1ConfigQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Config>>,
	TError = ApiError,
>(
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Config>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1ConfigQueryKey(getApiV1ConfigBody);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Config>>> = ({
		signal,
	}) => getApiV1Config(getApiV1ConfigBody, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Config>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1ConfigQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Config>>
>;
export type GetApiV1ConfigQueryError = ApiError;

export function useGetApiV1Config<
	TData = Awaited<ReturnType<typeof getApiV1Config>>,
	TError = ApiError,
>(
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Config>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Config>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Config>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Config<
	TData = Awaited<ReturnType<typeof getApiV1Config>>,
	TError = ApiError,
>(
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Config>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Config>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Config>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Config<
	TData = Awaited<ReturnType<typeof getApiV1Config>>,
	TError = ApiError,
>(
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Config>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get configuration
 */

export function useGetApiV1Config<
	TData = Awaited<ReturnType<typeof getApiV1Config>>,
	TError = ApiError,
>(
	getApiV1ConfigBody: GetApiV1ConfigBody,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getApiV1Config>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1ConfigQueryOptions(
		getApiV1ConfigBody,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Updates application configuration (only certain fields are updatable at runtime)
 * @summary Update configuration
 */
export type putApiV1ConfigResponse200 = {
	data: Config;
	status: 200;
};

export type putApiV1ConfigResponse400 = {
	data: ApiError;
	status: 400;
};

export type putApiV1ConfigResponse500 = {
	data: ApiError;
	status: 500;
};

export type putApiV1ConfigResponseSuccess = putApiV1ConfigResponse200 & {
	headers: Headers;
};
export type putApiV1ConfigResponseError = (
	| putApiV1ConfigResponse400
	| putApiV1ConfigResponse500
) & {
	headers: Headers;
};

export type putApiV1ConfigResponse =
	| putApiV1ConfigResponseSuccess
	| putApiV1ConfigResponseError;

export const getPutApiV1ConfigUrl = () => {
	return `/api/v1/config`;
};

export const putApiV1Config = async (
	putApiV1ConfigBody: PutApiV1ConfigBody,
	options?: RequestInit,
): Promise<putApiV1ConfigResponse> => {
	const res = await fetch(getPutApiV1ConfigUrl(), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(putApiV1ConfigBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: putApiV1ConfigResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as putApiV1ConfigResponse;
};

export const getPutApiV1ConfigMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiV1Config>>,
		TError,
		{ data: PutApiV1ConfigBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiV1Config>>,
	TError,
	{ data: PutApiV1ConfigBody },
	TContext
> => {
	const mutationKey = ["putApiV1Config"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiV1Config>>,
		{ data: PutApiV1ConfigBody }
	> = (props) => {
		const { data } = props ?? {};

		return putApiV1Config(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiV1ConfigMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiV1Config>>
>;
export type PutApiV1ConfigMutationBody = PutApiV1ConfigBody;
export type PutApiV1ConfigMutationError = ApiError;

/**
 * @summary Update configuration
 */
export const usePutApiV1Config = <TError = ApiError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiV1Config>>,
			TError,
			{ data: PutApiV1ConfigBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiV1Config>>,
	TError,
	{ data: PutApiV1ConfigBody },
	TContext
> => {
	return useMutation(getPutApiV1ConfigMutationOptions(options), queryClient);
};
