/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../../lib/custom-fetch";

import { customFetch } from "../../lib/custom-fetch";
import type {
	ApiError,
	PostApiV1WebhooksGithubBodyOne,
	PostApiV1WebhooksGithubBodyTwo,
	WebhookHealth,
	WebhookResp,
} from "../schemas";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Receives and processes GitHub webhook events with signature verification
 * @summary Process GitHub webhook
 */
export type postApiV1WebhooksGithubResponse200 = {
	data: WebhookResp;
	status: 200;
};

export type postApiV1WebhooksGithubResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1WebhooksGithubResponse401 = {
	data: ApiError;
	status: 401;
};

export type postApiV1WebhooksGithubResponse503 = {
	data: ApiError;
	status: 503;
};

export type postApiV1WebhooksGithubResponseSuccess =
	postApiV1WebhooksGithubResponse200 & {
		headers: Headers;
	};
export type postApiV1WebhooksGithubResponseError = (
	| postApiV1WebhooksGithubResponse400
	| postApiV1WebhooksGithubResponse401
	| postApiV1WebhooksGithubResponse503
) & {
	headers: Headers;
};

export type postApiV1WebhooksGithubResponse =
	| postApiV1WebhooksGithubResponseSuccess
	| postApiV1WebhooksGithubResponseError;

export const getPostApiV1WebhooksGithubUrl = () => {
	return `/api/v1/webhooks/github`;
};

export const postApiV1WebhooksGithub = async (
	postApiV1WebhooksGithubBody:
		| PostApiV1WebhooksGithubBodyOne
		| PostApiV1WebhooksGithubBodyTwo,
	options?: RequestInit,
): Promise<postApiV1WebhooksGithubResponse> => {
	return customFetch<postApiV1WebhooksGithubResponse>(
		getPostApiV1WebhooksGithubUrl(),
		{
			...options,
			method: "POST",
			body: JSON.stringify(postApiV1WebhooksGithubBody),
		},
	);
};

export const getPostApiV1WebhooksGithubMutationOptions = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1WebhooksGithub>>,
		TError,
		{ data: PostApiV1WebhooksGithubBodyOne | PostApiV1WebhooksGithubBodyTwo },
		TContext
	>;
	request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1WebhooksGithub>>,
	TError,
	{ data: PostApiV1WebhooksGithubBodyOne | PostApiV1WebhooksGithubBodyTwo },
	TContext
> => {
	const mutationKey = ["postApiV1WebhooksGithub"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1WebhooksGithub>>,
		{ data: PostApiV1WebhooksGithubBodyOne | PostApiV1WebhooksGithubBodyTwo }
	> = (props) => {
		const { data } = props ?? {};

		return postApiV1WebhooksGithub(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1WebhooksGithubMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1WebhooksGithub>>
>;
export type PostApiV1WebhooksGithubMutationBody =
	| PostApiV1WebhooksGithubBodyOne
	| PostApiV1WebhooksGithubBodyTwo;
export type PostApiV1WebhooksGithubMutationError = ErrorType<ApiError>;

/**
 * @summary Process GitHub webhook
 */
export const usePostApiV1WebhooksGithub = <
	TError = ErrorType<ApiError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1WebhooksGithub>>,
			TError,
			{ data: PostApiV1WebhooksGithubBodyOne | PostApiV1WebhooksGithubBodyTwo },
			TContext
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1WebhooksGithub>>,
	TError,
	{ data: PostApiV1WebhooksGithubBodyOne | PostApiV1WebhooksGithubBodyTwo },
	TContext
> => {
	return useMutation(
		getPostApiV1WebhooksGithubMutationOptions(options),
		queryClient,
	);
};
/**
 * Returns health status including registered event handlers
 * @summary Webhook handler health check
 */
export type getApiV1WebhooksHealthResponse200 = {
	data: WebhookHealth;
	status: 200;
};

export type getApiV1WebhooksHealthResponseSuccess =
	getApiV1WebhooksHealthResponse200 & {
		headers: Headers;
	};

export type getApiV1WebhooksHealthResponse =
	getApiV1WebhooksHealthResponseSuccess;

export const getGetApiV1WebhooksHealthUrl = () => {
	return `/api/v1/webhooks/health`;
};

export const getApiV1WebhooksHealth = async (
	options?: RequestInit,
): Promise<getApiV1WebhooksHealthResponse> => {
	return customFetch<getApiV1WebhooksHealthResponse>(
		getGetApiV1WebhooksHealthUrl(),
		{
			...options,
			method: "GET",
		},
	);
};

export const getGetApiV1WebhooksHealthQueryKey = () => {
	return [`/api/v1/webhooks/health`] as const;
};

export const getGetApiV1WebhooksHealthQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1WebhooksHealthQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1WebhooksHealth>>
	> = ({ signal }) => getApiV1WebhooksHealth({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1WebhooksHealthQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1WebhooksHealth>>
>;
export type GetApiV1WebhooksHealthQueryError = ErrorType<unknown>;

export function useGetApiV1WebhooksHealth<
	TData = Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
					TError,
					Awaited<ReturnType<typeof getApiV1WebhooksHealth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1WebhooksHealth<
	TData = Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
					TError,
					Awaited<ReturnType<typeof getApiV1WebhooksHealth>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1WebhooksHealth<
	TData = Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Webhook handler health check
 */

export function useGetApiV1WebhooksHealth<
	TData = Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1WebhooksHealth>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1WebhooksHealthQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
