/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ApiError,
	GetApiV1SessionsSessionIdTasksParams,
	PostApiV1SessionsSessionIdTasksTaskIdRetryBody,
	PostApiV1SessionsSessionIdTasksTaskIdSkipBody,
	Success,
	TaskList,
	TaskStatus,
} from "../schemas";

/**
 * Retrieve all tasks for a work session with status statistics and execution progress
 * @summary Get task list
 */
export type getApiV1SessionsSessionIdTasksResponse200 = {
	data: TaskList;
	status: 200;
};

export type getApiV1SessionsSessionIdTasksResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1SessionsSessionIdTasksResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1SessionsSessionIdTasksResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1SessionsSessionIdTasksResponseSuccess =
	getApiV1SessionsSessionIdTasksResponse200 & {
		headers: Headers;
	};
export type getApiV1SessionsSessionIdTasksResponseError = (
	| getApiV1SessionsSessionIdTasksResponse400
	| getApiV1SessionsSessionIdTasksResponse404
	| getApiV1SessionsSessionIdTasksResponse500
) & {
	headers: Headers;
};

export type getApiV1SessionsSessionIdTasksResponse =
	| getApiV1SessionsSessionIdTasksResponseSuccess
	| getApiV1SessionsSessionIdTasksResponseError;

export const getGetApiV1SessionsSessionIdTasksUrl = (
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/sessions/${sessionId}/tasks?${stringifiedParams}`
		: `/api/v1/sessions/${sessionId}/tasks`;
};

export const getApiV1SessionsSessionIdTasks = async (
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
	options?: RequestInit,
): Promise<getApiV1SessionsSessionIdTasksResponse> => {
	const res = await fetch(
		getGetApiV1SessionsSessionIdTasksUrl(sessionId, params),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1SessionsSessionIdTasksResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1SessionsSessionIdTasksResponse;
};

export const getGetApiV1SessionsSessionIdTasksQueryKey = (
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
) => {
	return [
		`/api/v1/sessions/${sessionId}/tasks`,
		...(params ? [params] : []),
	] as const;
};

export const getGetApiV1SessionsSessionIdTasksQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1SessionsSessionIdTasksQueryKey(sessionId, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>
	> = ({ signal }) =>
		getApiV1SessionsSessionIdTasks(sessionId, params, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!sessionId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1SessionsSessionIdTasksQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>
>;
export type GetApiV1SessionsSessionIdTasksQueryError = ApiError;

export function useGetApiV1SessionsSessionIdTasks<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
	TError = ApiError,
>(
	sessionId: string,
	params: undefined | GetApiV1SessionsSessionIdTasksParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsSessionIdTasks<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsSessionIdTasks<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get task list
 */

export function useGetApiV1SessionsSessionIdTasks<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
	TError = ApiError,
>(
	sessionId: string,
	params?: GetApiV1SessionsSessionIdTasksParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasks>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1SessionsSessionIdTasksQueryOptions(
		sessionId,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Retrieve detailed status information for a specific task including dependencies and execution result
 * @summary Get task status
 */
export type getApiV1SessionsSessionIdTasksTaskIdResponse200 = {
	data: TaskStatus;
	status: 200;
};

export type getApiV1SessionsSessionIdTasksTaskIdResponse400 = {
	data: ApiError;
	status: 400;
};

export type getApiV1SessionsSessionIdTasksTaskIdResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1SessionsSessionIdTasksTaskIdResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1SessionsSessionIdTasksTaskIdResponseSuccess =
	getApiV1SessionsSessionIdTasksTaskIdResponse200 & {
		headers: Headers;
	};
export type getApiV1SessionsSessionIdTasksTaskIdResponseError = (
	| getApiV1SessionsSessionIdTasksTaskIdResponse400
	| getApiV1SessionsSessionIdTasksTaskIdResponse404
	| getApiV1SessionsSessionIdTasksTaskIdResponse500
) & {
	headers: Headers;
};

export type getApiV1SessionsSessionIdTasksTaskIdResponse =
	| getApiV1SessionsSessionIdTasksTaskIdResponseSuccess
	| getApiV1SessionsSessionIdTasksTaskIdResponseError;

export const getGetApiV1SessionsSessionIdTasksTaskIdUrl = (
	sessionId: string,
	taskId: string,
) => {
	return `/api/v1/sessions/${sessionId}/tasks/${taskId}`;
};

export const getApiV1SessionsSessionIdTasksTaskId = async (
	sessionId: string,
	taskId: string,
	options?: RequestInit,
): Promise<getApiV1SessionsSessionIdTasksTaskIdResponse> => {
	const res = await fetch(
		getGetApiV1SessionsSessionIdTasksTaskIdUrl(sessionId, taskId),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1SessionsSessionIdTasksTaskIdResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1SessionsSessionIdTasksTaskIdResponse;
};

export const getGetApiV1SessionsSessionIdTasksTaskIdQueryKey = (
	sessionId: string,
	taskId: string,
) => {
	return [`/api/v1/sessions/${sessionId}/tasks/${taskId}`] as const;
};

export const getGetApiV1SessionsSessionIdTasksTaskIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
	TError = ApiError,
>(
	sessionId: string,
	taskId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1SessionsSessionIdTasksTaskIdQueryKey(sessionId, taskId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>
	> = ({ signal }) =>
		getApiV1SessionsSessionIdTasksTaskId(sessionId, taskId, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!(sessionId && taskId),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1SessionsSessionIdTasksTaskIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>
>;
export type GetApiV1SessionsSessionIdTasksTaskIdQueryError = ApiError;

export function useGetApiV1SessionsSessionIdTasksTaskId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
	TError = ApiError,
>(
	sessionId: string,
	taskId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsSessionIdTasksTaskId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
	TError = ApiError,
>(
	sessionId: string,
	taskId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
					TError,
					Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1SessionsSessionIdTasksTaskId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
	TError = ApiError,
>(
	sessionId: string,
	taskId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get task status
 */

export function useGetApiV1SessionsSessionIdTasksTaskId<
	TData = Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
	TError = ApiError,
>(
	sessionId: string,
	taskId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1SessionsSessionIdTasksTaskId>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1SessionsSessionIdTasksTaskIdQueryOptions(
		sessionId,
		taskId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Reset a failed task to in-progress status for re-execution. Task must be in failed status and not exceed retry limit.
 * @summary Retry task
 */
export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse200 = {
	data: Success;
	status: 200;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponseSuccess =
	postApiV1SessionsSessionIdTasksTaskIdRetryResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsSessionIdTasksTaskIdRetryResponseError = (
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponse400
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponse404
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponse409
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsSessionIdTasksTaskIdRetryResponse =
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponseSuccess
	| postApiV1SessionsSessionIdTasksTaskIdRetryResponseError;

export const getPostApiV1SessionsSessionIdTasksTaskIdRetryUrl = (
	sessionId: string,
	taskId: string,
) => {
	return `/api/v1/sessions/${sessionId}/tasks/${taskId}/retry`;
};

export const postApiV1SessionsSessionIdTasksTaskIdRetry = async (
	sessionId: string,
	taskId: string,
	postApiV1SessionsSessionIdTasksTaskIdRetryBody: PostApiV1SessionsSessionIdTasksTaskIdRetryBody,
	options?: RequestInit,
): Promise<postApiV1SessionsSessionIdTasksTaskIdRetryResponse> => {
	const res = await fetch(
		getPostApiV1SessionsSessionIdTasksTaskIdRetryUrl(sessionId, taskId),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsSessionIdTasksTaskIdRetryBody),
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1SessionsSessionIdTasksTaskIdRetryResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1SessionsSessionIdTasksTaskIdRetryResponse;
};

export const getPostApiV1SessionsSessionIdTasksTaskIdRetryMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>,
		TError,
		{
			sessionId: string;
			taskId: string;
			data: PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
		},
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>,
	TError,
	{
		sessionId: string;
		taskId: string;
		data: PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
	},
	TContext
> => {
	const mutationKey = ["postApiV1SessionsSessionIdTasksTaskIdRetry"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>,
		{
			sessionId: string;
			taskId: string;
			data: PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
		}
	> = (props) => {
		const { sessionId, taskId, data } = props ?? {};

		return postApiV1SessionsSessionIdTasksTaskIdRetry(
			sessionId,
			taskId,
			data,
			fetchOptions,
		);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsSessionIdTasksTaskIdRetryMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>
	>;
export type PostApiV1SessionsSessionIdTasksTaskIdRetryMutationBody =
	PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
export type PostApiV1SessionsSessionIdTasksTaskIdRetryMutationError = ApiError;

/**
 * @summary Retry task
 */
export const usePostApiV1SessionsSessionIdTasksTaskIdRetry = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>,
			TError,
			{
				sessionId: string;
				taskId: string;
				data: PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
			},
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdRetry>>,
	TError,
	{
		sessionId: string;
		taskId: string;
		data: PostApiV1SessionsSessionIdTasksTaskIdRetryBody;
	},
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsSessionIdTasksTaskIdRetryMutationOptions(options),
		queryClient,
	);
};
/**
 * Mark a task as skipped, removing it from execution queue. Skipped tasks are considered completed for dependency resolution.
 * @summary Skip task
 */
export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse200 = {
	data: Success;
	status: 200;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponseSuccess =
	postApiV1SessionsSessionIdTasksTaskIdSkipResponse200 & {
		headers: Headers;
	};
export type postApiV1SessionsSessionIdTasksTaskIdSkipResponseError = (
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponse400
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponse404
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponse409
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponse500
) & {
	headers: Headers;
};

export type postApiV1SessionsSessionIdTasksTaskIdSkipResponse =
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponseSuccess
	| postApiV1SessionsSessionIdTasksTaskIdSkipResponseError;

export const getPostApiV1SessionsSessionIdTasksTaskIdSkipUrl = (
	sessionId: string,
	taskId: string,
) => {
	return `/api/v1/sessions/${sessionId}/tasks/${taskId}/skip`;
};

export const postApiV1SessionsSessionIdTasksTaskIdSkip = async (
	sessionId: string,
	taskId: string,
	postApiV1SessionsSessionIdTasksTaskIdSkipBody: PostApiV1SessionsSessionIdTasksTaskIdSkipBody,
	options?: RequestInit,
): Promise<postApiV1SessionsSessionIdTasksTaskIdSkipResponse> => {
	const res = await fetch(
		getPostApiV1SessionsSessionIdTasksTaskIdSkipUrl(sessionId, taskId),
		{
			...options,
			method: "POST",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(postApiV1SessionsSessionIdTasksTaskIdSkipBody),
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1SessionsSessionIdTasksTaskIdSkipResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1SessionsSessionIdTasksTaskIdSkipResponse;
};

export const getPostApiV1SessionsSessionIdTasksTaskIdSkipMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>,
		TError,
		{
			sessionId: string;
			taskId: string;
			data: PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
		},
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>,
	TError,
	{
		sessionId: string;
		taskId: string;
		data: PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
	},
	TContext
> => {
	const mutationKey = ["postApiV1SessionsSessionIdTasksTaskIdSkip"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>,
		{
			sessionId: string;
			taskId: string;
			data: PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
		}
	> = (props) => {
		const { sessionId, taskId, data } = props ?? {};

		return postApiV1SessionsSessionIdTasksTaskIdSkip(
			sessionId,
			taskId,
			data,
			fetchOptions,
		);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1SessionsSessionIdTasksTaskIdSkipMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>
	>;
export type PostApiV1SessionsSessionIdTasksTaskIdSkipMutationBody =
	PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
export type PostApiV1SessionsSessionIdTasksTaskIdSkipMutationError = ApiError;

/**
 * @summary Skip task
 */
export const usePostApiV1SessionsSessionIdTasksTaskIdSkip = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>,
			TError,
			{
				sessionId: string;
				taskId: string;
				data: PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
			},
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1SessionsSessionIdTasksTaskIdSkip>>,
	TError,
	{
		sessionId: string;
		taskId: string;
		data: PostApiV1SessionsSessionIdTasksTaskIdSkipBody;
	},
	TContext
> => {
	return useMutation(
		getPostApiV1SessionsSessionIdTasksTaskIdSkipMutationOptions(options),
		queryClient,
	);
};
