/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated/issues/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedRepositoriesNameRouteImport } from './routes/_authenticated/repositories/$name'
import { Route as AuthenticatedIssuesIdRouteImport } from './routes/_authenticated/issues/$id'
import { Route as AuthenticatedAuditLogsIdRouteImport } from './routes/_authenticated/audit-logs/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoriesNameRoute =
  AuthenticatedRepositoriesNameRouteImport.update({
    id: '/repositories/$name',
    path: '/repositories/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesIdRoute = AuthenticatedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsIdRoute =
  AuthenticatedAuditLogsIdRouteImport.update({
    id: '/audit-logs/$id',
    path: '/audit-logs/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/repositories/$name': typeof AuthenticatedRepositoriesNameRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/repositories/$name': typeof AuthenticatedRepositoriesNameRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/audit-logs/$id': typeof AuthenticatedAuditLogsIdRoute
  '/_authenticated/issues/$id': typeof AuthenticatedIssuesIdRoute
  '/_authenticated/repositories/$name': typeof AuthenticatedRepositoriesNameRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs/$id'
    | '/issues/$id'
    | '/repositories/$name'
    | '/audit-logs/'
    | '/issues/'
    | '/repositories/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/audit-logs/$id'
    | '/issues/$id'
    | '/repositories/$name'
    | '/audit-logs'
    | '/issues'
    | '/repositories'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/audit-logs/$id'
    | '/_authenticated/issues/$id'
    | '/_authenticated/repositories/$name'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/issues/'
    | '/_authenticated/repositories/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/$name': {
      id: '/_authenticated/repositories/$name'
      path: '/repositories/$name'
      fullPath: '/repositories/$name'
      preLoaderRoute: typeof AuthenticatedRepositoriesNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$id': {
      id: '/_authenticated/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthenticatedIssuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs/$id': {
      id: '/_authenticated/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/audit-logs/$id'
      preLoaderRoute: typeof AuthenticatedAuditLogsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAuditLogsIdRoute: typeof AuthenticatedAuditLogsIdRoute
  AuthenticatedIssuesIdRoute: typeof AuthenticatedIssuesIdRoute
  AuthenticatedRepositoriesNameRoute: typeof AuthenticatedRepositoriesNameRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAuditLogsIdRoute: AuthenticatedAuditLogsIdRoute,
  AuthenticatedIssuesIdRoute: AuthenticatedIssuesIdRoute,
  AuthenticatedRepositoriesNameRoute: AuthenticatedRepositoriesNameRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
