/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as AuditLogsIndexRouteImport } from './routes/audit-logs/index'
import { Route as RepositoriesNameRouteImport } from './routes/repositories/$name'
import { Route as IssuesIdRouteImport } from './routes/issues/$id'
import { Route as AuditLogsIdRouteImport } from './routes/audit-logs/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIndexRoute = AuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesNameRoute = RepositoriesNameRouteImport.update({
  id: '/repositories/$name',
  path: '/repositories/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsIdRoute = AuditLogsIdRouteImport.update({
  id: '/audit-logs/$id',
  path: '/audit-logs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/repositories/$name': typeof RepositoriesNameRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/repositories/$name': typeof RepositoriesNameRoute
  '/audit-logs': typeof AuditLogsIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs/$id': typeof AuditLogsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/repositories/$name': typeof RepositoriesNameRoute
  '/audit-logs/': typeof AuditLogsIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs/$id'
    | '/issues/$id'
    | '/repositories/$name'
    | '/audit-logs/'
    | '/issues/'
    | '/repositories/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs/$id'
    | '/issues/$id'
    | '/repositories/$name'
    | '/audit-logs'
    | '/issues'
    | '/repositories'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/audit-logs/$id'
    | '/issues/$id'
    | '/repositories/$name'
    | '/audit-logs/'
    | '/issues/'
    | '/repositories/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuditLogsIdRoute: typeof AuditLogsIdRoute
  IssuesIdRoute: typeof IssuesIdRoute
  RepositoriesNameRoute: typeof RepositoriesNameRoute
  AuditLogsIndexRoute: typeof AuditLogsIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/': {
      id: '/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$name': {
      id: '/repositories/$name'
      path: '/repositories/$name'
      fullPath: '/repositories/$name'
      preLoaderRoute: typeof RepositoriesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs/$id': {
      id: '/audit-logs/$id'
      path: '/audit-logs/$id'
      fullPath: '/audit-logs/$id'
      preLoaderRoute: typeof AuditLogsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuditLogsIdRoute: AuditLogsIdRoute,
  IssuesIdRoute: IssuesIdRoute,
  RepositoriesNameRoute: RepositoriesNameRoute,
  AuditLogsIndexRoute: AuditLogsIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
