/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Litchi API
 * Automated development agent system - from GitHub Issue to Pull Request
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	ApiError,
	DeleteApiV1RepositoriesNameBody,
	DetectedProject,
	EffectiveConfig,
	GetApiV1RepositoriesParams,
	PaginatedResponseRepository,
	PostApiV1RepositoriesBody,
	PostApiV1RepositoriesNameDisableBody,
	PostApiV1RepositoriesNameEnableBody,
	PutApiV1RepositoriesNameBody,
	PutApiV1RepositoriesNameValidationConfigBody,
	Repository,
	Success,
	ValidationConfig,
} from "../schemas";

/**
 * Get all repository configurations with optional pagination and filtering
 * @summary List repositories
 */
export type getApiV1RepositoriesResponse200 = {
	data: PaginatedResponseRepository;
	status: 200;
};

export type getApiV1RepositoriesResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1RepositoriesResponseSuccess =
	getApiV1RepositoriesResponse200 & {
		headers: Headers;
	};
export type getApiV1RepositoriesResponseError =
	getApiV1RepositoriesResponse500 & {
		headers: Headers;
	};

export type getApiV1RepositoriesResponse =
	| getApiV1RepositoriesResponseSuccess
	| getApiV1RepositoriesResponseError;

export const getGetApiV1RepositoriesUrl = (
	params?: GetApiV1RepositoriesParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/api/v1/repositories?${stringifiedParams}`
		: `/api/v1/repositories`;
};

export const getApiV1Repositories = async (
	params?: GetApiV1RepositoriesParams,
	options?: RequestInit,
): Promise<getApiV1RepositoriesResponse> => {
	const res = await fetch(getGetApiV1RepositoriesUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1RepositoriesResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1RepositoriesResponse;
};

export const getGetApiV1RepositoriesQueryKey = (
	params?: GetApiV1RepositoriesParams,
) => {
	return [`/api/v1/repositories`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1RepositoriesQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1Repositories>>,
	TError = ApiError,
>(
	params?: GetApiV1RepositoriesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Repositories>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1RepositoriesQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1Repositories>>
	> = ({ signal }) => getApiV1Repositories(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1Repositories>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1RepositoriesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1Repositories>>
>;
export type GetApiV1RepositoriesQueryError = ApiError;

export function useGetApiV1Repositories<
	TData = Awaited<ReturnType<typeof getApiV1Repositories>>,
	TError = ApiError,
>(
	params: undefined | GetApiV1RepositoriesParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Repositories>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Repositories>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Repositories>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Repositories<
	TData = Awaited<ReturnType<typeof getApiV1Repositories>>,
	TError = ApiError,
>(
	params?: GetApiV1RepositoriesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Repositories>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1Repositories>>,
					TError,
					Awaited<ReturnType<typeof getApiV1Repositories>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1Repositories<
	TData = Awaited<ReturnType<typeof getApiV1Repositories>>,
	TError = ApiError,
>(
	params?: GetApiV1RepositoriesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Repositories>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List repositories
 */

export function useGetApiV1Repositories<
	TData = Awaited<ReturnType<typeof getApiV1Repositories>>,
	TError = ApiError,
>(
	params?: GetApiV1RepositoriesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1Repositories>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1RepositoriesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new repository configuration for processing
 * @summary Create repository
 */
export type postApiV1RepositoriesResponse201 = {
	data: Repository;
	status: 201;
};

export type postApiV1RepositoriesResponse400 = {
	data: ApiError;
	status: 400;
};

export type postApiV1RepositoriesResponse409 = {
	data: ApiError;
	status: 409;
};

export type postApiV1RepositoriesResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1RepositoriesResponseSuccess =
	postApiV1RepositoriesResponse201 & {
		headers: Headers;
	};
export type postApiV1RepositoriesResponseError = (
	| postApiV1RepositoriesResponse400
	| postApiV1RepositoriesResponse409
	| postApiV1RepositoriesResponse500
) & {
	headers: Headers;
};

export type postApiV1RepositoriesResponse =
	| postApiV1RepositoriesResponseSuccess
	| postApiV1RepositoriesResponseError;

export const getPostApiV1RepositoriesUrl = () => {
	return `/api/v1/repositories`;
};

export const postApiV1Repositories = async (
	postApiV1RepositoriesBody: PostApiV1RepositoriesBody,
	options?: RequestInit,
): Promise<postApiV1RepositoriesResponse> => {
	const res = await fetch(getPostApiV1RepositoriesUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(postApiV1RepositoriesBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1RepositoriesResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1RepositoriesResponse;
};

export const getPostApiV1RepositoriesMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1Repositories>>,
		TError,
		{ data: PostApiV1RepositoriesBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1Repositories>>,
	TError,
	{ data: PostApiV1RepositoriesBody },
	TContext
> => {
	const mutationKey = ["postApiV1Repositories"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1Repositories>>,
		{ data: PostApiV1RepositoriesBody }
	> = (props) => {
		const { data } = props ?? {};

		return postApiV1Repositories(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1RepositoriesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1Repositories>>
>;
export type PostApiV1RepositoriesMutationBody = PostApiV1RepositoriesBody;
export type PostApiV1RepositoriesMutationError = ApiError;

/**
 * @summary Create repository
 */
export const usePostApiV1Repositories = <TError = ApiError, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1Repositories>>,
			TError,
			{ data: PostApiV1RepositoriesBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1Repositories>>,
	TError,
	{ data: PostApiV1RepositoriesBody },
	TContext
> => {
	return useMutation(
		getPostApiV1RepositoriesMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete repository configuration by name
 * @summary Delete repository
 */
export type deleteApiV1RepositoriesNameResponse200 = {
	data: Success;
	status: 200;
};

export type deleteApiV1RepositoriesNameResponse404 = {
	data: ApiError;
	status: 404;
};

export type deleteApiV1RepositoriesNameResponse500 = {
	data: ApiError;
	status: 500;
};

export type deleteApiV1RepositoriesNameResponseSuccess =
	deleteApiV1RepositoriesNameResponse200 & {
		headers: Headers;
	};
export type deleteApiV1RepositoriesNameResponseError = (
	| deleteApiV1RepositoriesNameResponse404
	| deleteApiV1RepositoriesNameResponse500
) & {
	headers: Headers;
};

export type deleteApiV1RepositoriesNameResponse =
	| deleteApiV1RepositoriesNameResponseSuccess
	| deleteApiV1RepositoriesNameResponseError;

export const getDeleteApiV1RepositoriesNameUrl = (name: string) => {
	return `/api/v1/repositories/${name}`;
};

export const deleteApiV1RepositoriesName = async (
	name: string,
	deleteApiV1RepositoriesNameBody: DeleteApiV1RepositoriesNameBody,
	options?: RequestInit,
): Promise<deleteApiV1RepositoriesNameResponse> => {
	const res = await fetch(getDeleteApiV1RepositoriesNameUrl(name), {
		...options,
		method: "DELETE",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(deleteApiV1RepositoriesNameBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: deleteApiV1RepositoriesNameResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as deleteApiV1RepositoriesNameResponse;
};

export const getDeleteApiV1RepositoriesNameMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>,
		TError,
		{ name: string; data: DeleteApiV1RepositoriesNameBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>,
	TError,
	{ name: string; data: DeleteApiV1RepositoriesNameBody },
	TContext
> => {
	const mutationKey = ["deleteApiV1RepositoriesName"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>,
		{ name: string; data: DeleteApiV1RepositoriesNameBody }
	> = (props) => {
		const { name, data } = props ?? {};

		return deleteApiV1RepositoriesName(name, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteApiV1RepositoriesNameMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>
>;
export type DeleteApiV1RepositoriesNameMutationBody =
	DeleteApiV1RepositoriesNameBody;
export type DeleteApiV1RepositoriesNameMutationError = ApiError;

/**
 * @summary Delete repository
 */
export const useDeleteApiV1RepositoriesName = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>,
			TError,
			{ name: string; data: DeleteApiV1RepositoriesNameBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteApiV1RepositoriesName>>,
	TError,
	{ name: string; data: DeleteApiV1RepositoriesNameBody },
	TContext
> => {
	return useMutation(
		getDeleteApiV1RepositoriesNameMutationOptions(options),
		queryClient,
	);
};
/**
 * Get repository configuration by name (owner/repo format)
 * @summary Get repository
 */
export type getApiV1RepositoriesNameResponse200 = {
	data: Repository;
	status: 200;
};

export type getApiV1RepositoriesNameResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1RepositoriesNameResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1RepositoriesNameResponseSuccess =
	getApiV1RepositoriesNameResponse200 & {
		headers: Headers;
	};
export type getApiV1RepositoriesNameResponseError = (
	| getApiV1RepositoriesNameResponse404
	| getApiV1RepositoriesNameResponse500
) & {
	headers: Headers;
};

export type getApiV1RepositoriesNameResponse =
	| getApiV1RepositoriesNameResponseSuccess
	| getApiV1RepositoriesNameResponseError;

export const getGetApiV1RepositoriesNameUrl = (name: string) => {
	return `/api/v1/repositories/${name}`;
};

export const getApiV1RepositoriesName = async (
	name: string,
	options?: RequestInit,
): Promise<getApiV1RepositoriesNameResponse> => {
	const res = await fetch(getGetApiV1RepositoriesNameUrl(name), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1RepositoriesNameResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1RepositoriesNameResponse;
};

export const getGetApiV1RepositoriesNameQueryKey = (name: string) => {
	return [`/api/v1/repositories/${name}`] as const;
};

export const getGetApiV1RepositoriesNameQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiV1RepositoriesNameQueryKey(name);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1RepositoriesName>>
	> = ({ signal }) =>
		getApiV1RepositoriesName(name, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!name,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1RepositoriesNameQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1RepositoriesName>>
>;
export type GetApiV1RepositoriesNameQueryError = ApiError;

export function useGetApiV1RepositoriesName<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
	TError = ApiError,
>(
	name: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesName>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesName<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesName>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesName<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repository
 */

export function useGetApiV1RepositoriesName<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesName>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1RepositoriesNameQueryOptions(name, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update repository configuration by name
 * @summary Update repository
 */
export type putApiV1RepositoriesNameResponse200 = {
	data: Repository;
	status: 200;
};

export type putApiV1RepositoriesNameResponse400 = {
	data: ApiError;
	status: 400;
};

export type putApiV1RepositoriesNameResponse404 = {
	data: ApiError;
	status: 404;
};

export type putApiV1RepositoriesNameResponse500 = {
	data: ApiError;
	status: 500;
};

export type putApiV1RepositoriesNameResponseSuccess =
	putApiV1RepositoriesNameResponse200 & {
		headers: Headers;
	};
export type putApiV1RepositoriesNameResponseError = (
	| putApiV1RepositoriesNameResponse400
	| putApiV1RepositoriesNameResponse404
	| putApiV1RepositoriesNameResponse500
) & {
	headers: Headers;
};

export type putApiV1RepositoriesNameResponse =
	| putApiV1RepositoriesNameResponseSuccess
	| putApiV1RepositoriesNameResponseError;

export const getPutApiV1RepositoriesNameUrl = (name: string) => {
	return `/api/v1/repositories/${name}`;
};

export const putApiV1RepositoriesName = async (
	name: string,
	putApiV1RepositoriesNameBody: PutApiV1RepositoriesNameBody,
	options?: RequestInit,
): Promise<putApiV1RepositoriesNameResponse> => {
	const res = await fetch(getPutApiV1RepositoriesNameUrl(name), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(putApiV1RepositoriesNameBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: putApiV1RepositoriesNameResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as putApiV1RepositoriesNameResponse;
};

export const getPutApiV1RepositoriesNameMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiV1RepositoriesName>>,
		TError,
		{ name: string; data: PutApiV1RepositoriesNameBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiV1RepositoriesName>>,
	TError,
	{ name: string; data: PutApiV1RepositoriesNameBody },
	TContext
> => {
	const mutationKey = ["putApiV1RepositoriesName"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiV1RepositoriesName>>,
		{ name: string; data: PutApiV1RepositoriesNameBody }
	> = (props) => {
		const { name, data } = props ?? {};

		return putApiV1RepositoriesName(name, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiV1RepositoriesNameMutationResult = NonNullable<
	Awaited<ReturnType<typeof putApiV1RepositoriesName>>
>;
export type PutApiV1RepositoriesNameMutationBody = PutApiV1RepositoriesNameBody;
export type PutApiV1RepositoriesNameMutationError = ApiError;

/**
 * @summary Update repository
 */
export const usePutApiV1RepositoriesName = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiV1RepositoriesName>>,
			TError,
			{ name: string; data: PutApiV1RepositoriesNameBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiV1RepositoriesName>>,
	TError,
	{ name: string; data: PutApiV1RepositoriesNameBody },
	TContext
> => {
	return useMutation(
		getPutApiV1RepositoriesNameMutationOptions(options),
		queryClient,
	);
};
/**
 * Get the project detection result for a repository (language, tools, confidence)
 * @summary Get detection result
 */
export type getApiV1RepositoriesNameDetectionResponse200 = {
	data: DetectedProject;
	status: 200;
};

export type getApiV1RepositoriesNameDetectionResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1RepositoriesNameDetectionResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1RepositoriesNameDetectionResponseSuccess =
	getApiV1RepositoriesNameDetectionResponse200 & {
		headers: Headers;
	};
export type getApiV1RepositoriesNameDetectionResponseError = (
	| getApiV1RepositoriesNameDetectionResponse404
	| getApiV1RepositoriesNameDetectionResponse500
) & {
	headers: Headers;
};

export type getApiV1RepositoriesNameDetectionResponse =
	| getApiV1RepositoriesNameDetectionResponseSuccess
	| getApiV1RepositoriesNameDetectionResponseError;

export const getGetApiV1RepositoriesNameDetectionUrl = (name: string) => {
	return `/api/v1/repositories/${name}/detection`;
};

export const getApiV1RepositoriesNameDetection = async (
	name: string,
	options?: RequestInit,
): Promise<getApiV1RepositoriesNameDetectionResponse> => {
	const res = await fetch(getGetApiV1RepositoriesNameDetectionUrl(name), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1RepositoriesNameDetectionResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1RepositoriesNameDetectionResponse;
};

export const getGetApiV1RepositoriesNameDetectionQueryKey = (name: string) => {
	return [`/api/v1/repositories/${name}/detection`] as const;
};

export const getGetApiV1RepositoriesNameDetectionQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1RepositoriesNameDetectionQueryKey(name);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>
	> = ({ signal }) =>
		getApiV1RepositoriesNameDetection(name, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!name,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1RepositoriesNameDetectionQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>
>;
export type GetApiV1RepositoriesNameDetectionQueryError = ApiError;

export function useGetApiV1RepositoriesNameDetection<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
	TError = ApiError,
>(
	name: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameDetection<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameDetection<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get detection result
 */

export function useGetApiV1RepositoriesNameDetection<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameDetection>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1RepositoriesNameDetectionQueryOptions(
		name,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Trigger automatic project detection for a repository (detects language, framework, tools)
 * @summary Run project detection
 */
export type postApiV1RepositoriesNameDetectionResponse200 = {
	data: DetectedProject;
	status: 200;
};

export type postApiV1RepositoriesNameDetectionResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1RepositoriesNameDetectionResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1RepositoriesNameDetectionResponseSuccess =
	postApiV1RepositoriesNameDetectionResponse200 & {
		headers: Headers;
	};
export type postApiV1RepositoriesNameDetectionResponseError = (
	| postApiV1RepositoriesNameDetectionResponse404
	| postApiV1RepositoriesNameDetectionResponse500
) & {
	headers: Headers;
};

export type postApiV1RepositoriesNameDetectionResponse =
	| postApiV1RepositoriesNameDetectionResponseSuccess
	| postApiV1RepositoriesNameDetectionResponseError;

export const getPostApiV1RepositoriesNameDetectionUrl = (name: string) => {
	return `/api/v1/repositories/${name}/detection`;
};

export const postApiV1RepositoriesNameDetection = async (
	name: string,
	options?: RequestInit,
): Promise<postApiV1RepositoriesNameDetectionResponse> => {
	const res = await fetch(getPostApiV1RepositoriesNameDetectionUrl(name), {
		...options,
		method: "POST",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1RepositoriesNameDetectionResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1RepositoriesNameDetectionResponse;
};

export const getPostApiV1RepositoriesNameDetectionMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>,
		TError,
		{ name: string },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>,
	TError,
	{ name: string },
	TContext
> => {
	const mutationKey = ["postApiV1RepositoriesNameDetection"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>,
		{ name: string }
	> = (props) => {
		const { name } = props ?? {};

		return postApiV1RepositoriesNameDetection(name, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1RepositoriesNameDetectionMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>
>;

export type PostApiV1RepositoriesNameDetectionMutationError = ApiError;

/**
 * @summary Run project detection
 */
export const usePostApiV1RepositoriesNameDetection = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>,
			TError,
			{ name: string },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDetection>>,
	TError,
	{ name: string },
	TContext
> => {
	return useMutation(
		getPostApiV1RepositoriesNameDetectionMutationOptions(options),
		queryClient,
	);
};
/**
 * Disable a repository from processing incoming GitHub events
 * @summary Disable repository
 */
export type postApiV1RepositoriesNameDisableResponse200 = {
	data: Success;
	status: 200;
};

export type postApiV1RepositoriesNameDisableResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1RepositoriesNameDisableResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1RepositoriesNameDisableResponseSuccess =
	postApiV1RepositoriesNameDisableResponse200 & {
		headers: Headers;
	};
export type postApiV1RepositoriesNameDisableResponseError = (
	| postApiV1RepositoriesNameDisableResponse404
	| postApiV1RepositoriesNameDisableResponse500
) & {
	headers: Headers;
};

export type postApiV1RepositoriesNameDisableResponse =
	| postApiV1RepositoriesNameDisableResponseSuccess
	| postApiV1RepositoriesNameDisableResponseError;

export const getPostApiV1RepositoriesNameDisableUrl = (name: string) => {
	return `/api/v1/repositories/${name}/disable`;
};

export const postApiV1RepositoriesNameDisable = async (
	name: string,
	postApiV1RepositoriesNameDisableBody: PostApiV1RepositoriesNameDisableBody,
	options?: RequestInit,
): Promise<postApiV1RepositoriesNameDisableResponse> => {
	const res = await fetch(getPostApiV1RepositoriesNameDisableUrl(name), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(postApiV1RepositoriesNameDisableBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1RepositoriesNameDisableResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1RepositoriesNameDisableResponse;
};

export const getPostApiV1RepositoriesNameDisableMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>,
		TError,
		{ name: string; data: PostApiV1RepositoriesNameDisableBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>,
	TError,
	{ name: string; data: PostApiV1RepositoriesNameDisableBody },
	TContext
> => {
	const mutationKey = ["postApiV1RepositoriesNameDisable"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>,
		{ name: string; data: PostApiV1RepositoriesNameDisableBody }
	> = (props) => {
		const { name, data } = props ?? {};

		return postApiV1RepositoriesNameDisable(name, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1RepositoriesNameDisableMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>
>;
export type PostApiV1RepositoriesNameDisableMutationBody =
	PostApiV1RepositoriesNameDisableBody;
export type PostApiV1RepositoriesNameDisableMutationError = ApiError;

/**
 * @summary Disable repository
 */
export const usePostApiV1RepositoriesNameDisable = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>,
			TError,
			{ name: string; data: PostApiV1RepositoriesNameDisableBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameDisable>>,
	TError,
	{ name: string; data: PostApiV1RepositoriesNameDisableBody },
	TContext
> => {
	return useMutation(
		getPostApiV1RepositoriesNameDisableMutationOptions(options),
		queryClient,
	);
};
/**
 * Get the merged effective configuration (global + repository overrides)
 * @summary Get effective config
 */
export type getApiV1RepositoriesNameEffectiveConfigResponse200 = {
	data: EffectiveConfig;
	status: 200;
};

export type getApiV1RepositoriesNameEffectiveConfigResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1RepositoriesNameEffectiveConfigResponseSuccess =
	getApiV1RepositoriesNameEffectiveConfigResponse200 & {
		headers: Headers;
	};
export type getApiV1RepositoriesNameEffectiveConfigResponseError =
	getApiV1RepositoriesNameEffectiveConfigResponse500 & {
		headers: Headers;
	};

export type getApiV1RepositoriesNameEffectiveConfigResponse =
	| getApiV1RepositoriesNameEffectiveConfigResponseSuccess
	| getApiV1RepositoriesNameEffectiveConfigResponseError;

export const getGetApiV1RepositoriesNameEffectiveConfigUrl = (name: string) => {
	return `/api/v1/repositories/${name}/effective-config`;
};

export const getApiV1RepositoriesNameEffectiveConfig = async (
	name: string,
	options?: RequestInit,
): Promise<getApiV1RepositoriesNameEffectiveConfigResponse> => {
	const res = await fetch(getGetApiV1RepositoriesNameEffectiveConfigUrl(name), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1RepositoriesNameEffectiveConfigResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1RepositoriesNameEffectiveConfigResponse;
};

export const getGetApiV1RepositoriesNameEffectiveConfigQueryKey = (
	name: string,
) => {
	return [`/api/v1/repositories/${name}/effective-config`] as const;
};

export const getGetApiV1RepositoriesNameEffectiveConfigQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1RepositoriesNameEffectiveConfigQueryKey(name);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>
	> = ({ signal }) =>
		getApiV1RepositoriesNameEffectiveConfig(name, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!name,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1RepositoriesNameEffectiveConfigQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>
>;
export type GetApiV1RepositoriesNameEffectiveConfigQueryError = ApiError;

export function useGetApiV1RepositoriesNameEffectiveConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
	TError = ApiError,
>(
	name: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameEffectiveConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameEffectiveConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get effective config
 */

export function useGetApiV1RepositoriesNameEffectiveConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameEffectiveConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1RepositoriesNameEffectiveConfigQueryOptions(
		name,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Enable a repository to process incoming GitHub events
 * @summary Enable repository
 */
export type postApiV1RepositoriesNameEnableResponse200 = {
	data: Success;
	status: 200;
};

export type postApiV1RepositoriesNameEnableResponse404 = {
	data: ApiError;
	status: 404;
};

export type postApiV1RepositoriesNameEnableResponse500 = {
	data: ApiError;
	status: 500;
};

export type postApiV1RepositoriesNameEnableResponseSuccess =
	postApiV1RepositoriesNameEnableResponse200 & {
		headers: Headers;
	};
export type postApiV1RepositoriesNameEnableResponseError = (
	| postApiV1RepositoriesNameEnableResponse404
	| postApiV1RepositoriesNameEnableResponse500
) & {
	headers: Headers;
};

export type postApiV1RepositoriesNameEnableResponse =
	| postApiV1RepositoriesNameEnableResponseSuccess
	| postApiV1RepositoriesNameEnableResponseError;

export const getPostApiV1RepositoriesNameEnableUrl = (name: string) => {
	return `/api/v1/repositories/${name}/enable`;
};

export const postApiV1RepositoriesNameEnable = async (
	name: string,
	postApiV1RepositoriesNameEnableBody: PostApiV1RepositoriesNameEnableBody,
	options?: RequestInit,
): Promise<postApiV1RepositoriesNameEnableResponse> => {
	const res = await fetch(getPostApiV1RepositoriesNameEnableUrl(name), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(postApiV1RepositoriesNameEnableBody),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: postApiV1RepositoriesNameEnableResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as postApiV1RepositoriesNameEnableResponse;
};

export const getPostApiV1RepositoriesNameEnableMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>,
		TError,
		{ name: string; data: PostApiV1RepositoriesNameEnableBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>,
	TError,
	{ name: string; data: PostApiV1RepositoriesNameEnableBody },
	TContext
> => {
	const mutationKey = ["postApiV1RepositoriesNameEnable"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>,
		{ name: string; data: PostApiV1RepositoriesNameEnableBody }
	> = (props) => {
		const { name, data } = props ?? {};

		return postApiV1RepositoriesNameEnable(name, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostApiV1RepositoriesNameEnableMutationResult = NonNullable<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>
>;
export type PostApiV1RepositoriesNameEnableMutationBody =
	PostApiV1RepositoriesNameEnableBody;
export type PostApiV1RepositoriesNameEnableMutationError = ApiError;

/**
 * @summary Enable repository
 */
export const usePostApiV1RepositoriesNameEnable = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>,
			TError,
			{ name: string; data: PostApiV1RepositoriesNameEnableBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postApiV1RepositoriesNameEnable>>,
	TError,
	{ name: string; data: PostApiV1RepositoriesNameEnableBody },
	TContext
> => {
	return useMutation(
		getPostApiV1RepositoriesNameEnableMutationOptions(options),
		queryClient,
	);
};
/**
 * Get the validation configuration for a repository (formatting, linting, testing settings)
 * @summary Get validation config
 */
export type getApiV1RepositoriesNameValidationConfigResponse200 = {
	data: ValidationConfig;
	status: 200;
};

export type getApiV1RepositoriesNameValidationConfigResponse404 = {
	data: ApiError;
	status: 404;
};

export type getApiV1RepositoriesNameValidationConfigResponse500 = {
	data: ApiError;
	status: 500;
};

export type getApiV1RepositoriesNameValidationConfigResponseSuccess =
	getApiV1RepositoriesNameValidationConfigResponse200 & {
		headers: Headers;
	};
export type getApiV1RepositoriesNameValidationConfigResponseError = (
	| getApiV1RepositoriesNameValidationConfigResponse404
	| getApiV1RepositoriesNameValidationConfigResponse500
) & {
	headers: Headers;
};

export type getApiV1RepositoriesNameValidationConfigResponse =
	| getApiV1RepositoriesNameValidationConfigResponseSuccess
	| getApiV1RepositoriesNameValidationConfigResponseError;

export const getGetApiV1RepositoriesNameValidationConfigUrl = (
	name: string,
) => {
	return `/api/v1/repositories/${name}/validation-config`;
};

export const getApiV1RepositoriesNameValidationConfig = async (
	name: string,
	options?: RequestInit,
): Promise<getApiV1RepositoriesNameValidationConfigResponse> => {
	const res = await fetch(
		getGetApiV1RepositoriesNameValidationConfigUrl(name),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiV1RepositoriesNameValidationConfigResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiV1RepositoriesNameValidationConfigResponse;
};

export const getGetApiV1RepositoriesNameValidationConfigQueryKey = (
	name: string,
) => {
	return [`/api/v1/repositories/${name}/validation-config`] as const;
};

export const getGetApiV1RepositoriesNameValidationConfigQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetApiV1RepositoriesNameValidationConfigQueryKey(name);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>
	> = ({ signal }) =>
		getApiV1RepositoriesNameValidationConfig(name, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!name,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiV1RepositoriesNameValidationConfigQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>
>;
export type GetApiV1RepositoriesNameValidationConfigQueryError = ApiError;

export function useGetApiV1RepositoriesNameValidationConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
	TError = ApiError,
>(
	name: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameValidationConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
					TError,
					Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiV1RepositoriesNameValidationConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get validation config
 */

export function useGetApiV1RepositoriesNameValidationConfig<
	TData = Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
	TError = ApiError,
>(
	name: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiV1RepositoriesNameValidationConfig>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiV1RepositoriesNameValidationConfigQueryOptions(
		name,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update the validation configuration for a repository (formatting, linting, testing settings)
 * @summary Update validation config
 */
export type putApiV1RepositoriesNameValidationConfigResponse200 = {
	data: ValidationConfig;
	status: 200;
};

export type putApiV1RepositoriesNameValidationConfigResponse400 = {
	data: ApiError;
	status: 400;
};

export type putApiV1RepositoriesNameValidationConfigResponse404 = {
	data: ApiError;
	status: 404;
};

export type putApiV1RepositoriesNameValidationConfigResponse500 = {
	data: ApiError;
	status: 500;
};

export type putApiV1RepositoriesNameValidationConfigResponseSuccess =
	putApiV1RepositoriesNameValidationConfigResponse200 & {
		headers: Headers;
	};
export type putApiV1RepositoriesNameValidationConfigResponseError = (
	| putApiV1RepositoriesNameValidationConfigResponse400
	| putApiV1RepositoriesNameValidationConfigResponse404
	| putApiV1RepositoriesNameValidationConfigResponse500
) & {
	headers: Headers;
};

export type putApiV1RepositoriesNameValidationConfigResponse =
	| putApiV1RepositoriesNameValidationConfigResponseSuccess
	| putApiV1RepositoriesNameValidationConfigResponseError;

export const getPutApiV1RepositoriesNameValidationConfigUrl = (
	name: string,
) => {
	return `/api/v1/repositories/${name}/validation-config`;
};

export const putApiV1RepositoriesNameValidationConfig = async (
	name: string,
	putApiV1RepositoriesNameValidationConfigBody: PutApiV1RepositoriesNameValidationConfigBody,
	options?: RequestInit,
): Promise<putApiV1RepositoriesNameValidationConfigResponse> => {
	const res = await fetch(
		getPutApiV1RepositoriesNameValidationConfigUrl(name),
		{
			...options,
			method: "PUT",
			headers: { "Content-Type": "application/json", ...options?.headers },
			body: JSON.stringify(putApiV1RepositoriesNameValidationConfigBody),
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: putApiV1RepositoriesNameValidationConfigResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as putApiV1RepositoriesNameValidationConfigResponse;
};

export const getPutApiV1RepositoriesNameValidationConfigMutationOptions = <
	TError = ApiError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>,
		TError,
		{ name: string; data: PutApiV1RepositoriesNameValidationConfigBody },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>,
	TError,
	{ name: string; data: PutApiV1RepositoriesNameValidationConfigBody },
	TContext
> => {
	const mutationKey = ["putApiV1RepositoriesNameValidationConfig"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>,
		{ name: string; data: PutApiV1RepositoriesNameValidationConfigBody }
	> = (props) => {
		const { name, data } = props ?? {};

		return putApiV1RepositoriesNameValidationConfig(name, data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutApiV1RepositoriesNameValidationConfigMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>
	>;
export type PutApiV1RepositoriesNameValidationConfigMutationBody =
	PutApiV1RepositoriesNameValidationConfigBody;
export type PutApiV1RepositoriesNameValidationConfigMutationError = ApiError;

/**
 * @summary Update validation config
 */
export const usePutApiV1RepositoriesNameValidationConfig = <
	TError = ApiError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>,
			TError,
			{ name: string; data: PutApiV1RepositoriesNameValidationConfigBody },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putApiV1RepositoriesNameValidationConfig>>,
	TError,
	{ name: string; data: PutApiV1RepositoriesNameValidationConfigBody },
	TContext
> => {
	return useMutation(
		getPutApiV1RepositoriesNameValidationConfigMutationOptions(options),
		queryClient,
	);
};
